#!/usr/bin/env python3
"""Generate JE 1.26.2 items JSON with translations in en, ja, ko, zh."""
import json
import os

def t(en, ja, ko, zh):
    return {"en": en, "ja": ja, "ko": ko, "zh": zh}

def read_be_translations():
    be_path = os.path.join(os.path.dirname(__file__), "..", "data", "be_1.26.40.json")
    with open(be_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("item", {})

JE_ITEMS = [
    "air", "stone", "granite", "polished_granite", "diorite", "polished_diorite",
    "andesite", "polished_andesite", "deepslate", "cobbled_deepslate", "polished_deepslate",
    "calcite", "tuff", "tuff_slab", "tuff_stairs", "tuff_wall", "chiseled_tuff",
    "polished_tuff", "polished_tuff_slab", "polished_tuff_stairs", "polished_tuff_wall",
    "tuff_bricks", "tuff_brick_slab", "tuff_brick_stairs", "tuff_brick_wall",
    "chiseled_tuff_bricks", "sulfur", "potent_sulfur", "sulfur_slab", "sulfur_stairs",
    "sulfur_wall", "polished_sulfur", "polished_sulfur_slab", "polished_sulfur_stairs",
    "polished_sulfur_wall", "sulfur_bricks", "sulfur_brick_slab", "sulfur_brick_stairs",
    "sulfur_brick_wall", "chiseled_sulfur", "cinnabar", "cinnabar_slab", "cinnabar_stairs",
    "cinnabar_wall", "polished_cinnabar", "polished_cinnabar_slab",
    "polished_cinnabar_stairs", "polished_cinnabar_wall", "cinnabar_bricks",
    "cinnabar_brick_slab", "cinnabar_brick_stairs", "cinnabar_brick_wall",
    "chiseled_cinnabar", "dripstone_block", "grass_block", "dirt", "coarse_dirt", "podzol",
    "rooted_dirt", "mud", "crimson_nylium", "warped_nylium", "cobblestone", "oak_planks",
    "spruce_planks", "birch_planks", "jungle_planks", "acacia_planks", "cherry_planks",
    "dark_oak_planks", "pale_oak_planks", "mangrove_planks", "bamboo_planks",
    "crimson_planks", "warped_planks", "bamboo_mosaic", "oak_sapling", "spruce_sapling",
    "birch_sapling", "jungle_sapling", "acacia_sapling", "cherry_sapling",
    "dark_oak_sapling", "pale_oak_sapling", "mangrove_propagule", "bedrock", "sand",
    "suspicious_sand", "suspicious_gravel", "red_sand", "gravel", "coal_ore",
    "deepslate_coal_ore", "iron_ore", "deepslate_iron_ore", "copper_ore",
    "deepslate_copper_ore", "gold_ore", "deepslate_gold_ore", "redstone_ore",
    "deepslate_redstone_ore", "emerald_ore", "deepslate_emerald_ore", "lapis_ore",
    "deepslate_lapis_ore", "diamond_ore", "deepslate_diamond_ore", "nether_gold_ore",
    "nether_quartz_ore", "ancient_debris", "coal_block", "raw_iron_block",
    "raw_copper_block", "raw_gold_block", "heavy_core", "amethyst_block",
    "budding_amethyst", "iron_block", "copper_block", "gold_block", "diamond_block",
    "netherite_block", "chiseled_copper", "cut_copper", "cut_copper_stairs",
    "cut_copper_slab", "oak_log", "spruce_log", "birch_log", "jungle_log", "acacia_log",
    "cherry_log", "pale_oak_log", "dark_oak_log", "mangrove_log", "mangrove_roots",
    "muddy_mangrove_roots", "crimson_stem", "warped_stem", "bamboo_block",
    "stripped_oak_log", "stripped_spruce_log", "stripped_birch_log",
    "stripped_jungle_log", "stripped_acacia_log", "stripped_cherry_log",
    "stripped_dark_oak_log", "stripped_pale_oak_log", "stripped_mangrove_log",
    "stripped_crimson_stem", "stripped_warped_stem", "stripped_bamboo_block", "oak_wood",
    "spruce_wood", "birch_wood", "jungle_wood", "acacia_wood", "cherry_wood",
    "pale_oak_wood", "dark_oak_wood", "mangrove_wood", "crimson_hyphae", "warped_hyphae",
    "stripped_oak_wood", "stripped_spruce_wood", "stripped_birch_wood",
    "stripped_jungle_wood", "stripped_acacia_wood", "stripped_cherry_wood",
    "stripped_dark_oak_wood", "stripped_pale_oak_wood", "stripped_mangrove_wood",
    "stripped_crimson_hyphae", "stripped_warped_hyphae", "oak_leaves", "spruce_leaves",
    "birch_leaves", "jungle_leaves", "acacia_leaves", "cherry_leaves",
    "dark_oak_leaves", "pale_oak_leaves", "mangrove_leaves", "azalea_leaves",
    "flowering_azalea_leaves", "sponge", "wet_sponge", "glass", "tinted_glass",
    "lapis_block", "sandstone", "chiseled_sandstone", "cut_sandstone", "cobweb",
    "short_grass", "fern", "bush", "azalea", "flowering_azalea", "dead_bush",
    "firefly_bush", "dry_short_grass", "dry_tall_grass", "seagrass", "sea_pickle",
    "wool", "dandelion", "golden_dandelion", "open_eyeblossom", "closed_eyeblossom",
    "poppy", "blue_orchid", "allium", "azure_bluet", "red_tulip", "orange_tulip",
    "white_tulip", "pink_tulip", "oxeye_daisy", "cornflower", "lily_of_the_valley",
    "wither_rose", "torchflower", "pitcher_plant", "spore_blossom", "brown_mushroom",
    "red_mushroom", "crimson_fungus", "warped_fungus", "crimson_roots", "warped_roots",
    "nether_sprouts", "weeping_vines", "twisting_vines", "sugar_cane", "kelp",
    "pink_petals", "wildflowers", "leaf_litter", "moss_carpet", "moss_block",
    "pale_moss_carpet", "pale_hanging_moss", "pale_moss_block", "hanging_roots",
    "big_dripleaf", "small_dripleaf", "bamboo", "oak_slab", "spruce_slab", "birch_slab",
    "jungle_slab", "acacia_slab", "cherry_slab", "dark_oak_slab", "pale_oak_slab",
    "mangrove_slab", "bamboo_slab", "bamboo_mosaic_slab", "crimson_slab", "warped_slab",
    "stone_slab", "smooth_stone_slab", "sandstone_slab", "cut_sandstone_slab",
    "petrified_oak_slab", "cobblestone_slab", "brick_slab", "stone_brick_slab",
    "mud_brick_slab", "nether_brick_slab", "quartz_slab", "red_sandstone_slab",
    "cut_red_sandstone_slab", "purpur_slab", "prismarine_slab",
    "prismarine_brick_slab", "dark_prismarine_slab", "smooth_quartz",
    "smooth_red_sandstone", "smooth_sandstone", "smooth_stone", "bricks", "acacia_shelf",
    "bamboo_shelf", "birch_shelf", "cherry_shelf", "crimson_shelf", "dark_oak_shelf",
    "jungle_shelf", "mangrove_shelf", "oak_shelf", "pale_oak_shelf", "spruce_shelf",
    "warped_shelf", "bookshelf", "chiseled_bookshelf", "decorated_pot",
    "mossy_cobblestone", "obsidian", "torch", "end_rod", "chorus_plant", "chorus_flower",
    "purpur_block", "purpur_pillar", "purpur_stairs", "spawner", "creaking_heart",
    "chest", "crafting_table", "farmland", "furnace", "ladder", "cobblestone_stairs",
    "snow", "ice", "snow_block", "cactus", "cactus_flower", "clay", "jukebox",
    "oak_fence", "spruce_fence", "birch_fence", "jungle_fence", "acacia_fence",
    "cherry_fence", "dark_oak_fence", "pale_oak_fence", "mangrove_fence",
    "bamboo_fence", "crimson_fence", "warped_fence", "pumpkin", "carved_pumpkin",
    "jack_o_lantern", "netherrack", "soul_sand", "soul_soil", "basalt",
    "polished_basalt", "smooth_basalt", "soul_torch", "copper_torch", "glowstone",
    "infested_stone", "infested_cobblestone", "infested_stone_bricks",
    "infested_mossy_stone_bricks", "infested_cracked_stone_bricks",
    "infested_chiseled_stone_bricks", "infested_deepslate", "stone_bricks",
    "mossy_stone_bricks", "cracked_stone_bricks", "chiseled_stone_bricks", "packed_mud",
    "mud_bricks", "deepslate_bricks", "cracked_deepslate_bricks", "deepslate_tiles",
    "cracked_deepslate_tiles", "chiseled_deepslate", "reinforced_deepslate",
    "brown_mushroom_block", "red_mushroom_block", "mushroom_stem", "iron_bars",
    "copper_bars", "iron_chain", "copper_chain", "glass_pane", "melon", "vine",
    "glow_lichen", "resin_clump", "resin_block", "resin_bricks", "resin_brick_stairs",
    "resin_brick_slab", "resin_brick_wall", "chiseled_resin_bricks", "brick_stairs",
    "stone_brick_stairs", "mud_brick_stairs", "mycelium", "lily_pad", "nether_bricks",
    "cracked_nether_bricks", "chiseled_nether_bricks", "nether_brick_fence",
    "nether_brick_stairs", "sculk", "sculk_vein", "sculk_catalyst", "sculk_shrieker",
    "enchanting_table", "end_portal_frame", "end_stone", "end_stone_bricks", "dragon_egg",
    "sandstone_stairs", "ender_chest", "emerald_block", "oak_stairs", "spruce_stairs",
    "birch_stairs", "jungle_stairs", "acacia_stairs", "cherry_stairs",
    "dark_oak_stairs", "pale_oak_stairs", "mangrove_stairs", "bamboo_stairs",
    "bamboo_mosaic_stairs", "crimson_stairs", "warped_stairs", "command_block",
    "beacon", "cobblestone_wall", "mossy_cobblestone_wall", "brick_wall",
    "prismarine_wall", "red_sandstone_wall", "mossy_stone_brick_wall", "granite_wall",
    "stone_brick_wall", "mud_brick_wall", "nether_brick_wall", "andesite_wall",
    "red_nether_brick_wall", "sandstone_wall", "end_stone_brick_wall", "diorite_wall",
    "blackstone_wall", "polished_blackstone_wall", "polished_blackstone_brick_wall",
    "cobbled_deepslate_wall", "polished_deepslate_wall", "deepslate_brick_wall",
    "deepslate_tile_wall", "anvil", "chipped_anvil", "damaged_anvil",
    "chiseled_quartz_block", "quartz_block", "quartz_bricks", "quartz_pillar",
    "quartz_stairs", "barrier", "light", "hay_block", "carpet", "terracotta",
    "packed_ice", "dirt_path", "sunflower", "lilac", "rose_bush", "peony", "tall_grass",
    "large_fern", "stained_glass", "stained_glass_pane", "prismarine",
    "prismarine_bricks", "dark_prismarine", "prismarine_stairs",
    "prismarine_brick_stairs", "dark_prismarine_stairs", "sea_lantern", "red_sandstone",
    "chiseled_red_sandstone", "cut_red_sandstone", "red_sandstone_stairs",
    "repeating_command_block", "chain_command_block", "magma_block",
    "nether_wart_block", "warped_wart_block", "red_nether_bricks", "bone_block",
    "structure_void", "shulker_box", "glazed_terracotta", "turtle_egg", "sniffer_egg",
    "dried_ghast", "dead_tube_coral_block", "dead_brain_coral_block",
    "dead_bubble_coral_block", "dead_fire_coral_block", "dead_horn_coral_block",
    "tube_coral_block", "brain_coral_block", "bubble_coral_block", "fire_coral_block",
    "horn_coral_block", "tube_coral", "brain_coral", "bubble_coral", "fire_coral",
    "horn_coral", "dead_brain_coral", "dead_bubble_coral", "dead_fire_coral",
    "dead_horn_coral", "dead_tube_coral", "tube_coral_fan", "brain_coral_fan",
    "bubble_coral_fan", "fire_coral_fan", "horn_coral_fan", "dead_tube_coral_fan",
    "dead_brain_coral_fan", "dead_bubble_coral_fan", "dead_fire_coral_fan",
    "dead_horn_coral_fan", "blue_ice", "conduit", "polished_granite_stairs",
    "smooth_red_sandstone_stairs", "mossy_stone_brick_stairs", "polished_diorite_stairs",
    "mossy_cobblestone_stairs", "end_stone_brick_stairs", "stone_stairs",
    "smooth_sandstone_stairs", "smooth_quartz_stairs", "granite_stairs",
    "andesite_stairs", "red_nether_brick_stairs", "polished_andesite_stairs",
    "diorite_stairs", "cobbled_deepslate_stairs", "polished_deepslate_stairs",
    "deepslate_brick_stairs", "deepslate_tile_stairs", "polished_granite_slab",
    "smooth_red_sandstone_slab", "mossy_stone_brick_slab", "polished_diorite_slab",
    "mossy_cobblestone_slab", "end_stone_brick_slab", "smooth_sandstone_slab",
    "smooth_quartz_slab", "granite_slab", "andesite_slab", "red_nether_brick_slab",
    "polished_andesite_slab", "diorite_slab", "cobbled_deepslate_slab",
    "polished_deepslate_slab", "deepslate_brick_slab", "deepslate_tile_slab",
    "scaffolding", "redstone", "redstone_torch", "redstone_block", "repeater",
    "comparator", "piston", "sticky_piston", "slime_block", "honey_block", "observer",
    "hopper", "dispenser", "dropper", "lectern", "target", "lever", "lightning_rod",
    "daylight_detector", "sculk_sensor", "calibrated_sculk_sensor", "tripwire_hook",
    "trapped_chest", "tnt", "redstone_lamp", "note_block", "stone_button",
    "polished_blackstone_button", "oak_button", "spruce_button", "birch_button",
    "jungle_button", "acacia_button", "cherry_button", "dark_oak_button",
    "pale_oak_button", "mangrove_button", "bamboo_button", "crimson_button",
    "warped_button", "stone_pressure_plate", "polished_blackstone_pressure_plate",
    "light_weighted_pressure_plate", "heavy_weighted_pressure_plate",
    "oak_pressure_plate", "spruce_pressure_plate", "birch_pressure_plate",
    "jungle_pressure_plate", "acacia_pressure_plate", "cherry_pressure_plate",
    "dark_oak_pressure_plate", "pale_oak_pressure_plate", "mangrove_pressure_plate",
    "bamboo_pressure_plate", "crimson_pressure_plate", "warped_pressure_plate",
    "iron_door", "oak_door", "spruce_door", "birch_door", "jungle_door",
    "acacia_door", "cherry_door", "dark_oak_door", "pale_oak_door", "mangrove_door",
    "bamboo_door", "crimson_door", "warped_door", "copper_door", "iron_trapdoor",
    "oak_trapdoor", "spruce_trapdoor", "birch_trapdoor", "jungle_trapdoor",
    "acacia_trapdoor", "cherry_trapdoor", "dark_oak_trapdoor", "pale_oak_trapdoor",
    "mangrove_trapdoor", "bamboo_trapdoor", "crimson_trapdoor", "warped_trapdoor",
    "copper_trapdoor", "oak_fence_gate", "spruce_fence_gate", "birch_fence_gate",
    "jungle_fence_gate", "acacia_fence_gate", "cherry_fence_gate",
    "dark_oak_fence_gate", "pale_oak_fence_gate", "mangrove_fence_gate",
    "bamboo_fence_gate", "crimson_fence_gate", "warped_fence_gate", "powered_rail",
    "detector_rail", "rail", "activator_rail", "saddle", "harness", "minecart",
    "chest_minecart", "furnace_minecart", "tnt_minecart", "hopper_minecart",
    "carrot_on_a_stick", "warped_fungus_on_a_stick", "phantom_membrane", "elytra",
    "oak_boat", "oak_chest_boat", "spruce_boat", "spruce_chest_boat", "birch_boat",
    "birch_chest_boat", "jungle_boat", "jungle_chest_boat", "acacia_boat",
    "acacia_chest_boat", "cherry_boat", "cherry_chest_boat", "dark_oak_boat",
    "dark_oak_chest_boat", "pale_oak_boat", "pale_oak_chest_boat", "mangrove_boat",
    "mangrove_chest_boat", "bamboo_raft", "bamboo_chest_raft", "structure_block",
    "jigsaw", "test_block", "test_instance_block", "turtle_helmet", "turtle_scute",
    "armadillo_scute", "wolf_armor", "flint_and_steel", "bowl", "apple", "bow", "arrow",
    "coal", "charcoal", "diamond", "emerald", "lapis_lazuli", "quartz", "amethyst_shard",
    "raw_iron", "iron_ingot", "raw_copper", "copper_ingot", "raw_gold", "gold_ingot",
    "netherite_ingot", "netherite_scrap", "wooden_sword", "wooden_shovel",
    "wooden_pickaxe", "wooden_axe", "wooden_hoe", "copper_sword", "copper_shovel",
    "copper_pickaxe", "copper_axe", "copper_hoe", "stone_sword", "stone_shovel",
    "stone_pickaxe", "stone_axe", "stone_hoe", "golden_sword", "golden_shovel",
    "golden_pickaxe", "golden_axe", "golden_hoe", "iron_sword", "iron_shovel",
    "iron_pickaxe", "iron_axe", "iron_hoe", "diamond_sword", "diamond_shovel",
    "diamond_pickaxe", "diamond_axe", "diamond_hoe", "netherite_sword",
    "netherite_shovel", "netherite_pickaxe", "netherite_axe", "netherite_hoe", "stick",
    "mushroom_stew", "string", "feather", "gunpowder", "wheat_seeds", "wheat", "bread",
    "leather_helmet", "leather_chestplate", "leather_leggings", "leather_boots",
    "copper_helmet", "copper_chestplate", "copper_leggings", "copper_boots",
    "chainmail_helmet", "chainmail_chestplate", "chainmail_leggings", "chainmail_boots",
    "iron_helmet", "iron_chestplate", "iron_leggings", "iron_boots", "diamond_helmet",
    "diamond_chestplate", "diamond_leggings", "diamond_boots", "golden_helmet",
    "golden_chestplate", "golden_leggings", "golden_boots", "netherite_helmet",
    "netherite_chestplate", "netherite_leggings", "netherite_boots", "flint", "porkchop",
    "cooked_porkchop", "painting", "golden_apple", "enchanted_golden_apple", "oak_sign",
    "spruce_sign", "birch_sign", "jungle_sign", "acacia_sign", "cherry_sign",
    "dark_oak_sign", "pale_oak_sign", "mangrove_sign", "bamboo_sign", "crimson_sign",
    "warped_sign", "oak_hanging_sign", "spruce_hanging_sign", "birch_hanging_sign",
    "jungle_hanging_sign", "acacia_hanging_sign", "cherry_hanging_sign",
    "dark_oak_hanging_sign", "pale_oak_hanging_sign", "mangrove_hanging_sign",
    "bamboo_hanging_sign", "crimson_hanging_sign", "warped_hanging_sign", "bucket",
    "water_bucket", "lava_bucket", "powder_snow_bucket", "snowball", "leather",
    "milk_bucket", "pufferfish_bucket", "salmon_bucket", "cod_bucket",
    "tropical_fish_bucket", "axolotl_bucket", "sulfur_cube_bucket", "tadpole_bucket",
    "brick", "clay_ball", "dried_kelp_block", "paper", "book", "slime_ball", "egg",
    "blue_egg", "brown_egg", "compass", "recovery_compass", "bundle", "dyed_bundle",
    "fishing_rod", "clock", "spyglass", "glowstone_dust", "cod", "salmon",
    "tropical_fish", "pufferfish", "cooked_cod", "cooked_salmon", "ink_sac",
    "glow_ink_sac", "cocoa_beans", "dye", "bone_meal", "bone", "sugar", "cake", "bed",
    "cookie", "crafter", "filled_map", "shears", "melon_slice", "dried_kelp",
    "pumpkin_seeds", "melon_seeds", "beef", "cooked_beef", "chicken", "cooked_chicken",
    "rotten_flesh", "ender_pearl", "blaze_rod", "ghast_tear", "gold_nugget",
    "nether_wart", "glass_bottle", "potion", "spider_eye", "fermented_spider_eye",
    "blaze_powder", "magma_cream", "brewing_stand", "cauldron", "ender_eye",
    "glistering_melon_slice", "chicken_spawn_egg", "cow_spawn_egg", "pig_spawn_egg",
    "sheep_spawn_egg", "camel_spawn_egg", "donkey_spawn_egg", "horse_spawn_egg",
    "mule_spawn_egg", "cat_spawn_egg", "parrot_spawn_egg", "wolf_spawn_egg",
    "armadillo_spawn_egg", "bat_spawn_egg", "bee_spawn_egg", "fox_spawn_egg",
    "goat_spawn_egg", "llama_spawn_egg", "ocelot_spawn_egg", "panda_spawn_egg",
    "polar_bear_spawn_egg", "rabbit_spawn_egg", "axolotl_spawn_egg", "cod_spawn_egg",
    "dolphin_spawn_egg", "frog_spawn_egg", "glow_squid_spawn_egg", "nautilus_spawn_egg",
    "pufferfish_spawn_egg", "salmon_spawn_egg", "squid_spawn_egg", "tadpole_spawn_egg",
    "tropical_fish_spawn_egg", "turtle_spawn_egg", "allay_spawn_egg",
    "mooshroom_spawn_egg", "sniffer_spawn_egg", "sulfur_cube_spawn_egg",
    "copper_golem_spawn_egg", "iron_golem_spawn_egg", "snow_golem_spawn_egg",
    "trader_llama_spawn_egg", "villager_spawn_egg", "wandering_trader_spawn_egg",
    "bogged_spawn_egg", "camel_husk_spawn_egg", "drowned_spawn_egg", "husk_spawn_egg",
    "parched_spawn_egg", "skeleton_spawn_egg", "skeleton_horse_spawn_egg",
    "stray_spawn_egg", "wither_spawn_egg", "wither_skeleton_spawn_egg",
    "zombie_spawn_egg", "zombie_horse_spawn_egg", "zombie_nautilus_spawn_egg",
    "zombie_villager_spawn_egg", "cave_spider_spawn_egg", "spider_spawn_egg",
    "breeze_spawn_egg", "creaking_spawn_egg", "creeper_spawn_egg",
    "elder_guardian_spawn_egg", "guardian_spawn_egg", "phantom_spawn_egg",
    "silverfish_spawn_egg", "slime_spawn_egg", "warden_spawn_egg", "witch_spawn_egg",
    "evoker_spawn_egg", "pillager_spawn_egg", "ravager_spawn_egg",
    "vindicator_spawn_egg", "vex_spawn_egg", "blaze_spawn_egg", "ghast_spawn_egg",
    "happy_ghast_spawn_egg", "hoglin_spawn_egg", "magma_cube_spawn_egg",
    "piglin_spawn_egg", "piglin_brute_spawn_egg", "strider_spawn_egg",
    "zoglin_spawn_egg", "zombified_piglin_spawn_egg", "ender_dragon_spawn_egg",
    "enderman_spawn_egg", "endermite_spawn_egg", "shulker_spawn_egg",
    "experience_bottle", "fire_charge", "wind_charge", "writable_book", "written_book",
    "breeze_rod", "mace", "item_frame", "glow_item_frame", "flower_pot", "carrot",
    "potato", "baked_potato", "poisonous_potato", "map", "golden_carrot",
    "skeleton_skull", "wither_skeleton_skull", "player_head", "zombie_head",
    "creeper_head", "dragon_head", "piglin_head", "nether_star", "pumpkin_pie",
    "firework_rocket", "firework_star", "enchanted_book", "nether_brick", "resin_brick",
    "prismarine_shard", "prismarine_crystals", "rabbit", "cooked_rabbit", "rabbit_stew",
    "rabbit_foot", "rabbit_hide", "armor_stand", "copper_horse_armor",
    "iron_horse_armor", "golden_horse_armor", "diamond_horse_armor",
    "netherite_horse_armor", "leather_horse_armor", "lead", "name_tag",
    "command_block_minecart", "mutton", "cooked_mutton", "banner", "end_crystal",
    "chorus_fruit", "popped_chorus_fruit", "torchflower_seeds", "pitcher_pod",
    "beetroot", "beetroot_seeds", "beetroot_soup", "dragon_breath", "splash_potion",
    "spectral_arrow", "tipped_arrow", "lingering_potion", "shield", "wooden_spear",
    "stone_spear", "copper_spear", "iron_spear", "golden_spear", "diamond_spear",
    "netherite_spear", "totem_of_undying", "shulker_shell", "iron_nugget",
    "copper_nugget", "knowledge_book", "debug_stick", "music_disc_13", "music_disc_cat",
    "music_disc_blocks", "music_disc_bounce", "music_disc_chirp", "music_disc_creator",
    "music_disc_creator_music_box", "music_disc_far", "music_disc_lava_chicken",
    "music_disc_mall", "music_disc_mellohi", "music_disc_stal", "music_disc_strad",
    "music_disc_ward", "music_disc_11", "music_disc_wait", "music_disc_otherside",
    "music_disc_relic", "music_disc_5", "music_disc_pigstep", "music_disc_precipice",
    "music_disc_tears", "disc_fragment_5", "trident", "nautilus_shell",
    "iron_nautilus_armor", "golden_nautilus_armor", "diamond_nautilus_armor",
    "netherite_nautilus_armor", "copper_nautilus_armor", "heart_of_the_sea",
    "crossbow", "suspicious_stew", "loom", "flower_banner_pattern",
    "creeper_banner_pattern", "skull_banner_pattern", "mojang_banner_pattern",
    "globe_banner_pattern", "piglin_banner_pattern", "flow_banner_pattern",
    "guster_banner_pattern", "field_masoned_banner_pattern",
    "bordure_indented_banner_pattern", "goat_horn", "composter", "barrel", "smoker",
    "blast_furnace", "cartography_table", "fletching_table", "grindstone",
    "smithing_table", "stonecutter", "bell", "lantern", "soul_lantern",
    "copper_lantern", "sweet_berries", "glow_berries", "campfire", "soul_campfire",
    "shroomlight", "honeycomb", "bee_nest", "beehive", "honey_bottle",
    "honeycomb_block", "lodestone", "crying_obsidian", "blackstone", "blackstone_slab",
    "blackstone_stairs", "gilded_blackstone", "polished_blackstone",
    "polished_blackstone_slab", "polished_blackstone_stairs",
    "chiseled_polished_blackstone", "polished_blackstone_bricks",
    "polished_blackstone_brick_slab", "polished_blackstone_brick_stairs",
    "cracked_polished_blackstone_bricks", "respawn_anchor", "candle",
    "small_amethyst_bud", "medium_amethyst_bud", "large_amethyst_bud",
    "amethyst_cluster", "pointed_dripstone", "sulfur_spike", "ochre_froglight",
    "verdant_froglight", "pearlescent_froglight", "frogspawn", "echo_shard", "brush",
    "netherite_upgrade_smithing_template", "sentry_armor_trim_smithing_template",
    "dune_armor_trim_smithing_template", "coast_armor_trim_smithing_template",
    "wild_armor_trim_smithing_template", "ward_armor_trim_smithing_template",
    "eye_armor_trim_smithing_template", "vex_armor_trim_smithing_template",
    "tide_armor_trim_smithing_template", "snout_armor_trim_smithing_template",
    "rib_armor_trim_smithing_template", "spire_armor_trim_smithing_template",
    "wayfinder_armor_trim_smithing_template", "shaper_armor_trim_smithing_template",
    "silence_armor_trim_smithing_template", "raiser_armor_trim_smithing_template",
    "host_armor_trim_smithing_template", "flow_armor_trim_smithing_template",
    "bolt_armor_trim_smithing_template", "angler_pottery_sherd",
    "archer_pottery_sherd", "arms_up_pottery_sherd", "blade_pottery_sherd",
    "brewer_pottery_sherd", "burn_pottery_sherd", "danger_pottery_sherd",
    "explorer_pottery_sherd", "flow_pottery_sherd", "friend_pottery_sherd",
    "guster_pottery_sherd", "heart_pottery_sherd", "heartbreak_pottery_sherd",
    "howl_pottery_sherd", "miner_pottery_sherd", "mourner_pottery_sherd",
    "plenty_pottery_sherd", "prize_pottery_sherd", "scrape_pottery_sherd",
    "sheaf_pottery_sherd", "shelter_pottery_sherd", "skull_pottery_sherd",
    "snort_pottery_sherd", "copper_grate", "copper_bulb", "copper_chest",
    "copper_golem_statue", "trial_spawner", "trial_key", "ominous_trial_key",
    "vault", "ominous_bottle",
]

JE_EXCLUSIVE = {
    "sulfur": t("Sulfur", "硫黄", "유황", "硫磺"),
    "potent_sulfur": t("Potent Sulfur", "強力な硫黄", "강력한 유황", "强效硫磺"),
    "sulfur_slab": t("Sulfur Slab", "硫黄のハーフブロック", "유황 반 블록", "硫磺台阶"),
    "sulfur_stairs": t("Sulfur Stairs", "硫黄の階段", "유황 계단", "硫磺楼梯"),
    "sulfur_wall": t("Sulfur Wall", "硫黄の塀", "유황 담장", "硫磺墙"),
    "polished_sulfur": t("Polished Sulfur", "磨り砂糖の硫黄", "다듬은 유황", "磨制硫磺"),
    "polished_sulfur_slab": t("Polished Sulfur Slab", "磨り砂糖の硫黄ハーフブロック", "다듬은 유황 반 블록", "磨制硫磺台阶"),
    "polished_sulfur_stairs": t("Polished Sulfur Stairs", "磨り砂糖の硫黄階段", "다듬은 유황 계단", "磨制硫磺楼梯"),
    "polished_sulfur_wall": t("Polished Sulfur Wall", "磨り砂糖の硫黄の塀", "다듬은 유황 담장", "磨制硫磺墙"),
    "sulfur_bricks": t("Sulfur Bricks", "硫黄のレンガ", "유황 벽돌", "硫磺砖"),
    "sulfur_brick_slab": t("Sulfur Brick Slab", "硫黄レンガのハーフブロック", "유황 벽돌 반 블록", "硫磺砖台阶"),
    "sulfur_brick_stairs": t("Sulfur Brick Stairs", "硫黄レンガの階段", "유황 벽돌 계단", "硫磺砖楼梯"),
    "sulfur_brick_wall": t("Sulfur Brick Wall", "硫黄レンガの塀", "유황 벽돌 담장", "硫磺砖墙"),
    "chiseled_sulfur": t("Chiseled Sulfur", "刻み硫黄", "조각 유황", "錾制硫磺"),
    "cinnabar": t("Cinnabar", "朱砂", "주사", "朱砂"),
    "cinnabar_slab": t("Cinnabar Slab", "朱砂のハーフブロック", "주사 반 블록", "朱砂台阶"),
    "cinnabar_stairs": t("Cinnabar Stairs", "朱砂の階段", "주사 계단", "朱砂楼梯"),
    "cinnabar_wall": t("Cinnabar Wall", "朱砂の塀", "주사 담장", "朱砂墙"),
    "polished_cinnabar": t("Polished Cinnabar", "磨り砂糖の朱砂", "다듬은 주사", "磨制朱砂"),
    "polished_cinnabar_slab": t("Polished Cinnabar Slab", "磨り砂糖の朱砂ハーフブロック", "다듬은 주사 반 블록", "磨制朱砂台阶"),
    "polished_cinnabar_stairs": t("Polished Cinnabar Stairs", "磨り砂糖の朱砂階段", "다듬은 주사 계단", "磨制朱砂楼梯"),
    "polished_cinnabar_wall": t("Polished Cinnabar Wall", "磨り砂糖の朱砂の塀", "다듬은 주사 담장", "磨制朱砂墙"),
    "cinnabar_bricks": t("Cinnabar Bricks", "朱砂のレンガ", "주사 벽돌", "朱砂砖"),
    "cinnabar_brick_slab": t("Cinnabar Brick Slab", "朱砂レンガのハーフブロック", "주사 벽돌 반 블록", "朱砂砖台阶"),
    "cinnabar_brick_stairs": t("Cinnabar Brick Stairs", "朱砂レンガの階段", "주사 벽돌 계단", "朱砂砖楼梯"),
    "cinnabar_brick_wall": t("Cinnabar Brick Wall", "朱砂レンガの塀", "주사 벽돌 담장", "朱砂砖墙"),
    "chiseled_cinnabar": t("Chiseled Cinnabar", "刻み朱砂", "조각 주사", "錾制朱砂"),
    "firefly_bush": t("Firefly Bush", "ホタルの茂み", "반딧불이 덤불", "萤火虫灌木"),
    "dry_short_grass": t("Dry Short Grass", "乾いた短い草", "마른 짧은 풀", "干枯短草"),
    "dry_tall_grass": t("Dry Tall Grass", "乾いた高い草", "마른 긴 풀", "干枯高草"),
    "wildflowers": t("Wildflowers", "野の花", "들꽃", "野花"),
    "leaf_litter": t("Leaf Litter", "落ち葉", "낙엽", "落叶堆"),
    "pale_moss_carpet": t("Pale Moss Carpet", "淡い苔カーペット", "창백한 이끼 카펫", "苍白苔毯"),
    "pale_hanging_moss": t("Pale Hanging Moss", "淡い蔓苔", "창백한 늘어진 이끼", "苍白垂苔"),
    "pale_moss_block": t("Pale Moss Block", "淡い苔ブロック", "창백한 이끼 블록", "苍白苔块"),
    "sulfur_spike": t("Sulfur Spike", "硫黄の突起", "유황 뾰족 돌기", "硫磺尖刺"),
    "sulfur_cube_bucket": t("Sulfur Cube Bucket", "硫黄キューブ入りバケツ", "유황 큐브 양동이", "硫磺立方体桶"),
    "sulfur_cube_spawn_egg": t("Sulfur Cube Spawn Egg", "硫黄キューブのスポーンエッグ", "유황 큐브 생성 알", "硫磺立方体刷怪蛋"),
    "nautilus_spawn_egg": t("Nautilus Spawn Egg", "ナウティラスのスポーンエッグ", "나우틸러스 생성 알", "鹦鹉螺刷怪蛋"),
    "copper_golem_spawn_egg": t("Copper Golem Spawn Egg", "銅ゴーレムのスポーンエッグ", "구리 골렘 생성 알", "铜傀儡刷怪蛋"),
    "copper_golem_statue": t("Copper Golem Statue", "銅ゴーレムの像", "구리 골렘 조각상", "铜傀儡雕像"),
    "camel_husk_spawn_egg": t("Camel Husk Spawn Egg", "カメルハスクのスポーンエッグ", "카멜 하스크 생성 알", "骆驼尸壳刷怪蛋"),
    "parched_spawn_egg": t("Parched Spawn Egg", "パーチドのスポーンエッグ", "퍼CHED 생성 알", "干裂刷怪蛋"),
    "dried_ghast": t("Dried Ghast", "乾いたガスト", "마른 가스트", "干枯恶魂"),
    "zombie_nautilus_spawn_egg": t("Zombie Nautilus Spawn Egg", "ゾンビナウティラスのスポーンエッグ", "좀비 나우틸러스 생성 알", "僵尸鹦鹉螺刷怪蛋"),
    "music_disc_bounce": t("Music Disc", "ミュージックディスク", "음악 디스크", "音乐唱片"),
    "music_disc_creator": t("Music Disc", "ミュージックディスク", "음악 디스크", "音乐唱片"),
    "music_disc_creator_music_box": t("Music Disc", "ミュージックディスク", "음악 디스크", "音乐唱片"),
    "music_disc_lava_chicken": t("Music Disc", "ミュージックディスク", "음악 디스크", "音乐唱片"),
    "music_disc_precipice": t("Music Disc", "ミュージックディスク", "음악 디스크", "音乐唱片"),
    "music_disc_tears": t("Music Disc", "ミュージックディスク", "음악 디스크", "音乐唱片"),
    "tuff_slab": t("Tuff Slab", "凝灰岩のハーフブロック", "트러프 반 블록", "凝灰岩台阶"),
    "tuff_stairs": t("Tuff Stairs", "凝灰岩の階段", "트러프 계단", "凝灰岩楼梯"),
    "tuff_wall": t("Tuff Wall", "凝灰岩の塀", "트러프 담장", "凝灰岩墙"),
    "chiseled_tuff": t("Chiseled Tuff", "刻み凝灰岩", "조각 트러프", "錾制凝灰岩"),
    "polished_tuff": t("Polished Tuff", "磨り凝灰岩", "다듬은 트러프", "磨制凝灰岩"),
    "polished_tuff_slab": t("Polished Tuff Slab", "磨り凝灰岩のハーフブロック", "다듬은 트러프 반 블록", "磨制凝灰岩台阶"),
    "polished_tuff_stairs": t("Polished Tuff Stairs", "磨り凝灰岩の階段", "다듬은 트러프 계단", "磨制凝灰岩楼梯"),
    "polished_tuff_wall": t("Polished Tuff Wall", "磨り凝灰岩の塀", "다듬은 트러프 담장", "磨制凝灰岩墙"),
    "tuff_bricks": t("Tuff Bricks", "凝灰岩のレンガ", "트러프 벽돌", "凝灰岩砖"),
    "tuff_brick_slab": t("Tuff Brick Slab", "凝灰岩レンガのハーフブロック", "트러프 벽돌 반 블록", "凝灰岩砖台阶"),
    "tuff_brick_stairs": t("Tuff Brick Stairs", "凝灰岩レンガの階段", "트러프 벽돌 계단", "凝灰岩砖楼梯"),
    "tuff_brick_wall": t("Tuff Brick Wall", "凝灰岩レンガの塀", "트러프 벽돌 담장", "凝灰岩砖墙"),
    "chiseled_tuff_bricks": t("Chiseled Tuff Bricks", "刻み凝灰岩レンガ", "조각 트러프 벽돌", "錾制凝灰岩砖"),
    "copper_torch": t("Copper Torch", "銅の松明", "구리 횃불", "铜火把"),
    "copper_bars": t("Copper Bars", "銅の棒", "구리 선반", "铜栏杆"),
    "copper_chain": t("Copper Chain", "銅のチェーン", "구리 체인", "铜锁链"),
    "copper_lantern": t("Copper Lantern", "銅のランタン", "구리 랜턴", "铜灯笼"),
    "copper_grate": t("Copper Grate", "銅のグレート", "구리 격자", "铜格栅"),
    "copper_bulb": t("Copper Bulb", "銅の電球", "구리 전구", "铜灯泡"),
    "copper_chest": t("Copper Chest", "銅のチェスト", "구리 상자", "铜箱子"),
    "heavy_core": t("Heavy Core", "ヘビーコア", "무거운 코어", "沉重核心"),
    "test_block": t("Test Block", "テストブロック", "테스트 블록", "测试方块"),
    "test_instance_block": t("Test Instance Block", "テストインスタンスブロック", "테스트 인스턴스 블록", "测试实例方块"),
    "creaking_heart": t("Creaking Heart", "軋む心", "딱딱거리는 심장", "嘎吱之心"),
    "suspicious_sand": t("Suspicious Sand", "怪しい砂", "수상한 모래", "可疑的沙子"),
    "suspicious_gravel": t("Suspicious Gravel", "怪しい砂利", "수상한 자갈", "可疑的沙砾"),
    "bush": t("Bush", "茂み", "덤불", "灌木"),
    "golden_dandelion": t("Golden Dandelion", "金色のタンポポ", "황금 민들레", "金色蒲公英"),
    "open_eyeblossom": t("Open Eyeblossom", "開いたアイバイラッソム", "피어 있는 눈꽃", "盛开的眼花"),
    "closed_eyeblossom": t("Closed Eyeblossom", "閉じたアイバイラッソム", "감긴 눈꽃", "闭合的眼花"),
}

BE_TO_JE_NAME_MAP = {
    "tuff_block": "tuff",
    "smooth_stone": "smooth_stone",
    "brick_block": "bricks",
    "tall_grass": "tall_grass",
    "large_fern": "large_fern",
    "flowering_azalea_leaves": "flowering_azalea_leaves",
    "azalea_leaves_flowered": "flowering_azalea_leaves",
}

def snake_to_title(name):
    return name.replace("_", " ").title()

def make_je_translations(item_id, be_translations):
    if item_id in JE_EXCLUSIVE:
        return JE_EXCLUSIVE[item_id]

    if item_id in be_translations:
        return {
            "en": be_translations[item_id].get("en", snake_to_title(item_id)),
            "ja": be_translations[item_id].get("ja", snake_to_title(item_id)),
            "ko": be_translations[item_id].get("ko", snake_to_title(item_id)),
            "zh": be_translations[item_id].get("zh", snake_to_title(item_id)),
        }

    be_key = None
    if item_id in BE_TO_JE_NAME_MAP:
        be_key = BE_TO_JE_NAME_MAP[item_id]

    if be_key and be_key in be_translations:
        return {
            "en": be_translations[be_key].get("en", snake_to_title(item_id)),
            "ja": be_translations[be_key].get("ja", snake_to_title(item_id)),
            "ko": be_translations[be_key].get("ko", snake_to_title(item_id)),
            "zh": be_translations[be_key].get("zh", snake_to_title(item_id)),
        }

    title = snake_to_title(item_id)
    return {"en": title, "ja": title, "ko": title, "zh": title}

def main():
    be_trans = read_be_translations()
    result = {}
    for item_id in JE_ITEMS:
        result[item_id] = make_je_translations(item_id, be_trans)

    out_path = os.path.join(os.path.dirname(__file__), "je_items.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(result)} items -> {out_path}")

if __name__ == "__main__":
    main()
