#!/usr/bin/env python3
"""Generate JE 1.26.4 sounds JSON with translations in en, ja, ko, zh."""
import json
import os
import re


def t(en, ja, ko, zh):
    return {"en": en, "ja": ja, "ko": ko, "zh": zh}


def read_be_translations():
    be_path = os.path.join(os.path.dirname(__file__), "..", "data", "be_1.26.40.json")
    with open(be_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("sound", {})


def extract_je_sound_ids():
    java_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "mcje", "decompiled_cfr", "net", "minecraft", "sounds", "SoundEvents.java"
    )
    with open(java_path, "r", encoding="utf-8") as f:
        content = f.read()
    ids = set()
    for m in re.finditer(r'\.register(?:ForHolder)?\("([^"]+)"\)', content):
        ids.add(m.group(1))
    return sorted(ids)


# Block name translations
BN = {
    "amethyst_block": ("Amethyst Block", "アメジストブロック", "자수정 블록", "紫水晶块"),
    "amethyst_cluster": ("Amethyst Cluster", "アメジストのクラスター", "자수정 클러스터", "紫水晶簇"),
    "ancient_debris": ("Ancient Debris", "古代の残骸", "고대 잔해", "远古残骸"),
    "anvil": ("Anvil", "金床", "모루", "铁砧"),
    "azalea": ("Azalea", "ツツジ", "아젤리아", "杜鹃花"),
    "azalea_leaves": ("Azalea Leaves", "ツツジの葉", "아젤리아 잎", "杜鹃树叶"),
    "bamboo": ("Bamboo", "竹", "대나무", "竹子"),
    "bamboo_sapling": ("Bamboo Sapling", "竹の苗木", "대나무 묘목", "竹树苗"),
    "bamboo_wood": ("Bamboo Wood", "竹の木材", "대나무 나무", "竹木"),
    "bamboo_wood_door": ("Bamboo Wood Door", "竹のドア", "대나무 문", "竹木门"),
    "bamboo_wood_trapdoor": ("Bamboo Wood Trapdoor", "竹のトラップドア", "대나무 다락문", "竹木活板门"),
    "bamboo_wood_button": ("Bamboo Wood Button", "竹のボタン", "대나무 버튼", "竹木按钮"),
    "bamboo_wood_pressure_plate": ("Bamboo Wood Pressure Plate", "竹の感圧板", "대나무 압력판", "竹木压力板"),
    "bamboo_wood_fence_gate": ("Bamboo Wood Fence Gate", "竹のフェンスゲート", "대나무 울타리 문", "竹木栅栏门"),
    "bamboo_wood_hanging_sign": ("Bamboo Wood Hanging Sign", "竹のつるし看板", "대나무 매달린 간판", "竹木悬挂式告示牌"),
    "barrel": ("Barrel", "樽", "통", "木桶"),
    "basalt": ("Basalt", "玄武岩", "현무암", "玄武岩"),
    "beacon": ("Beacon", "ビーコン", "신호기", "信标"),
    "beehive": ("Beehive", "キーストック", "벌집", "蜂巢"),
    "bell": ("Bell", "鐘", "종", "钟"),
    "big_dripleaf": ("Big Dripleaf", "大きな雫草", "큰 방울풀", "大型垂滴叶"),
    "blastfurnace": ("Blast Furnace", "溶鉱炉", "용광로", "高炉"),
    "bone_block": ("Bone Block", "骨ブロック", "뼈 블록", "骨块"),
    "brewing_stand": ("Brewing Stand", "醸造台", "양조대", "酿造台"),
    "bubble_column": ("Bubble Column", "バブル列", "버블 기둥", "气泡柱"),
    "cactus_flower": ("Cactus Flower", "サボテンの花", "선인장 꽃", "仙人掌花"),
    "cake": ("Cake", "ケーキ", "케이크", "蛋糕"),
    "calcite": ("Calcite", "方解石", "방해석", "方解石"),
    "campfire": ("Campfire", "キャンプファイヤー", "캠프파이어", "营火"),
    "candle": ("Candle", "ロウソク", "양초", "蜡烛"),
    "cave_vines": ("Cave Vines", "洞窟の蔦", "동굴 덩굴", "洞穴藤蔓"),
    "chain": ("Chain", "鎖", "사슬", "锁链"),
    "cherry_wood": ("Cherry Wood", "桜の木材", "벚꽃 나무", "樱花木"),
    "cherry_sapling": ("Cherry Sapling", "桜の苗木", "벚꽃 묘목", "樱花树苗"),
    "cherry_leaves": ("Cherry Leaves", "桜の葉", "벚꽃 잎", "樱花树叶"),
    "cherry_wood_hanging_sign": ("Cherry Wood Hanging Sign", "桜のつるし看板", "벚꽃 매달린 간판", "樱花木悬挂式告示牌"),
    "cherry_wood_door": ("Cherry Wood Door", "桜のドア", "벚꽃 문", "樱花木门"),
    "cherry_wood_trapdoor": ("Cherry Wood Trapdoor", "桜のトラップドア", "벚꽃 다락문", "樱花木活板门"),
    "cherry_wood_button": ("Cherry Wood Button", "桜のボタン", "벚꽃 버튼", "樱花木按钮"),
    "cherry_wood_pressure_plate": ("Cherry Wood Pressure Plate", "桜の感圧板", "벚꽃 압력판", "樱花木压力板"),
    "cherry_wood_fence_gate": ("Cherry Wood Fence Gate", "桜のフェンスゲート", "벚꽃 울타리 문", "樱花木栅栏门"),
    "chest": ("Chest", "チェスト", "상자", "箱子"),
    "chiseled_bookshelf": ("Chiseled Bookshelf", "模様付き本棚", "조각된 책장", "雕纹书架"),
    "chorus_flower": ("Chorus Flower", "チューリップの花", "콰이어스 플라워", "紫颂花"),
    "cobweb": ("Cobweb", "クモの巣", "거미줄", "蜘蛛网"),
    "comparator": ("Comparator", "レッドストーンコンパレーター", "레드스톤 비교기", "红石比较器"),
    "composter": ("Composter", "コンポスター", "퇴비통", "堆肥桶"),
    "conduit": ("Conduit", " conduit", " conduit", "导管"),
    "copper_bulb": ("Copper Bulb", "銅の電球", "구리 전구", "铜灯泡"),
    "copper": ("Copper", "銅", "구리", "铜"),
    "copper_chest": ("Copper Chest", "銅のチェスト", "구리 상자", "铜箱子"),
    "copper_chest_weathered": ("Weathered Copper Chest", "風化した銅のチェスト", "바랜 구리 상자", "风化铜箱子"),
    "copper_chest_oxidized": ("Oxidized Copper Chest", "酸化した銅のチェスト", "산화된 구리 상자", "氧化铜箱子"),
    "copper_door": ("Copper Door", "銅のドア", "구리 문", "铜门"),
    "copper_grate": ("Copper Grate", "銅の格子", "구리 격자", "铜格栅"),
    "copper_trapdoor": ("Copper Trapdoor", "銅のトラップドア", "구리 다락문", "铜活板门"),
    "copper_golem_statue": ("Copper Golem Statue", "銅ゴーレムの像", "구리 골렘 동상", "铜傀儡雕像"),
    "coral_block": ("Coral Block", "珊瑚ブロック", "산호 블록", "珊瑚块"),
    "crafter": ("Crafter", "作業台", "제작기", "合成器"),
    "creaking_heart": ("Creaking Heart", "軋む心臓", "우당opard心脏", "嘎吱之心"),
    "crop": ("Crop", "作物", "작물", "作物"),
    "deadbush": ("Dead Bush", "枯れ木", "마른 덤불", "枯萎的灌木"),
    "decorated_pot": ("Decorated Pot", "飾り付きの壺", "장식된 항아리", "装饰陶罐"),
    "deepslate": ("Deepslate", "深層岩", "심층암", "深板岩"),
    "deepslate_bricks": ("Deepslate Bricks", "深層岩レンガ", "심층암 벽돌", "深板岩砖"),
    "deepslate_tiles": ("Deepslate Tiles", "深層岩タイル", "심층암 타일", "深板岩瓦块"),
    "dispenser": ("Dispenser", "ディスペンサー", "디스펜서", "发射器"),
    "dried_ghast": ("Dried Ghast", "乾いたガスト", "마른 가스트", "枯萎的恶魂"),
    "dripstone_block": ("Dripstone Block", "滴り石ブロック", "방울석 블록", "滴水石块"),
    "dry_grass": ("Dry Grass", "乾いた草", "마른 풀", "干草"),
    "enchantment_table": ("Enchantment Table", "付魔台", "인CHANTING TABLE", "附魔台"),
    "ender_chest": ("Ender Chest", "エンダーチェ스트", "エンダーチェスト", "末影箱"),
    "end_gateway": ("End Gateway", "エンドゲートウェ이", "엔드 게이트웨이", "末地折跃门"),
    "end_portal_frame": ("End Portal Frame", "エンドポータルフレーム", "엔드 포탈 프레임", "末地传送门框架"),
    "end_portal": ("End Portal", "エンドポータル", "엔드 포탈", "末地传送门"),
    "eyeblossom": ("Eyeblossom", "眼球花", "눈꽃", "眼眸花"),
    "fence_gate": ("Fence Gate", "フェンスゲート", "울타리 문", "栅栏门"),
    "fire": ("Fire", "火", "불", "火"),
    "firefly_bush": ("Firefly Bush", "ホタルの茂み", "반딧불이 덤불", "萤火虫丛"),
    "flowering_azalea": ("Flowering Azalea", "花のツツジ", "꽃핀 아젤리아", "盛开的杜鹃花"),
    "froglight": ("Froglight", "カエルライト", "개구리 등불", "蛙明灯"),
    "frogspawn": ("Frogspawn", "カエルの卵", "개구리 알", "青蛙卵"),
    "furnace": ("Furnace", "かまど", "화로", "熔炉"),
    "gilded_blackstone": ("Gilded Blackstone", "金のべっこう岩", "금이 칠한 흑요석", "镶金黑石"),
    "glass": ("Glass", "ガラス", "유리", "玻璃"),
    "growing_plant": ("Growing Plant", "成長する植物", "자라는 식물", "生长的植物"),
    "grindstone": ("Grindstone", "砥石", "연마대", "砂轮"),
    "hanging_roots": ("Hanging Roots", "つる根", "매달린 뿌리", "垂根"),
    "hanging_sign": ("Hanging Sign", "つるし看板", "매달린 간판", "悬挂式告示牌"),
    "heavy_core": ("Heavy Core", "重い核", "무거운 코어", "重型核心"),
    "honey_block": ("Honey Block", "ハチミツブロック", "꿀 블록", "蜂蜜块"),
    "iron": ("Iron", "鉄", "철", "铁"),
    "iron_door": ("Iron Door", "鉄のドア", "철 문", "铁门"),
    "iron_trapdoor": ("Iron Trapdoor", "鉄のトラップドア", "철 다락문", "铁活板门"),
    "ladder": ("Ladder", "はしご", "사다리", "梯子"),
    "lantern": ("Lantern", "ランタン", "랜턴", "灯笼"),
    "large_amethyst_bud": ("Large Amethyst Bud", "大きなアメジストのつぼみ", "큰 자수정 새싹", "大型紫水晶芽"),
    "lava": ("Lava", "溶岩", "용암", "岩浆"),
    "leaf_litter": ("Leaf Litter", "落ち葉", "낙엽", "落叶层"),
    "lever": ("Lever", "レバー", "레버", "拉杆"),
    "lodestone": ("Lodestone", "磁石", "나침반", "磁石"),
    "lily_pad": ("Lily Pad", "睡蓮の葉", "연꽃 잎", "睡莲叶"),
    "mangrove_roots": ("Mangrove Roots", "マングローブの根", "맹그로브 뿌리", "红树根"),
    "medium_amethyst_bud": ("Medium Amethyst Bud", "中くらいのアメジストのつぼみ", "중간 자수정 새싹", "中型紫水晶芽"),
    "metal": ("Metal", "金属", "금속", "金属"),
    "metal_pressure_plate": ("Metal Pressure Plate", "金属の感圧板", "금속 압력판", "金属压力板"),
    "moss_carpet": ("Moss Carpet", "苔のカーペット", "이끼 카펫", "苔毯"),
    "moss": ("Moss", "苔", "이끼", "苔藓"),
    "mud": ("Mud", "泥", "진흙", "泥巴"),
    "mud_bricks": ("Mud Bricks", "泥レンガ", "진흙 벽돌", "泥砖"),
    "muddy_mangrove_roots": ("Muddy Mangrove Roots", "泥だらけのマングローブの根", "진흙 맹그로브 뿌리", "沾泥的红树根"),
    "nether_bricks": ("Nether Bricks", "ネザーレンガ", "네더 벽돌", "下界砖"),
    "nether_wart": ("Nether Wart", "ネザーウォート", "네더워트", "下界疣"),
    "nether_wood": ("Nether Wood", "ネザーの木材", "네더 나무", "下界木"),
    "nether_wood_door": ("Nether Wood Door", "ネザーのドア", "네더 문", "下界木门"),
    "nether_wood_trapdoor": ("Nether Wood Trapdoor", "ネザーのトラップドア", "네더 다락문", "下界木活板门"),
    "nether_wood_button": ("Nether Wood Button", "ネザーのボタン", "네더 버튼", "下界木按钮"),
    "nether_wood_pressure_plate": ("Nether Wood Pressure Plate", "ネザーの感圧板", "네더 압력판", "下界木压力板"),
    "nether_wood_fence_gate": ("Nether Wood Fence Gate", "ネザーのフェンスゲート", "네더 울타리 문", "下界木栅栏门"),
    "nether_wood_hanging_sign": ("Nether Wood Hanging Sign", "ネザーのつるし看板", "네더 매달린 간판", "下界木悬挂式告示牌"),
    "nether_gold_ore": ("Nether Gold Ore", "ネザーゴールド鉱石", "네더 금 광석", "下界金矿石"),
    "nether_ore": ("Nether Ore", "ネザー鉱石", "네더 광석", "下界矿石"),
    "netherite_block": ("Netherite Block", "ネザライトブロック", "네더라이트 블록", "下界合金块"),
    "netherrack": ("Netherrack", "ネザー岩", "네더암", "下界岩"),
    "note_block": ("Note Block", "音符ブロック", "노트 블록", "音符盒"),
    "nylium": ("Nylium", "ニリウム", "나일륨", "菌丝体"),
    "nether_sprouts": ("Nether Sprouts", "ネザースプラウト", "네더 새싹", "下界苗"),
    "fungus": ("Fungus", "菌糸", "균사", "菌类"),
    "weeping_vines": ("Weeping Vines", "泣きゼニグサ", "우는 덩굴", "垂泪藤"),
    "wart_block": ("Wart Block", "ウォートブロック", "워트 블록", "疣块"),
    "stem": ("Stem", "幹", "줄기", "茎"),
    "packed_mud": ("Packed Mud", "詰まった泥", "단단한 진흙", "泥坯"),
    "pale_hanging_moss": ("Pale Hanging Moss", "蒼白のつるし苔", "창백한 매달린 이끼", "苍白垂苔"),
    "pink_petals": ("Pink Petals", "ピンクの花びら", "핑크 꽃잎", "粉红花瓣"),
    "piston": ("Piston", "ピストン", "피스톤", "活塞"),
    "pointed_dripstone": ("Pointed Dripstone", "尖った滴り石", "뾰족한 방울석", "滴水石锥"),
    "polished_deepslate": ("Polished Deepslate", "磨いた深層岩", "연마된 심층암", "磨制深板岩"),
    "portal": ("Portal", "ポータル", "포탈", "传送门"),
    "powder_snow": ("Powder Snow", "粉雪", "가루 눈", "细雪"),
    "pumpkin": ("Pumpkin", "カボチャ", "호박", "南瓜"),
    "redstone_torch": ("Redstone Torch", "レッドストーントーチ", "레드스톤 토치", "红石火把"),
    "resin": ("Resin", "レジン", "레진", "树脂"),
    "resin_bricks": ("Resin Bricks", "レジンレンガ", "레진 벽돌", "树脂砖"),
    "respawn_anchor": ("Respawn Anchor", "リスポーンアンカー", "리스폰 앵커", "重生锚"),
    "roots": ("Roots", "根", "뿌리", "根"),
    "rooted_dirt": ("Rooted Dirt", "根付いた土", "뿌리박힌 흙", "缠根泥土"),
    "sand": ("Sand", "砂", "모래", "沙子"),
    "scaffolding": ("Scaffolding", "足場", "비계", "脚手架"),
    "sculk": ("Sculk", "スカルク", "스컬크", "幽匿块"),
    "sculk_catalyst": ("Sculk Catalyst", "スカルクカタリスト", "스컬크 촉매", "幽匿催发体"),
    "sculk_sensor": ("Sculk Sensor", "スカルクセンサー", "스컬크 센서", "幽匿感测体"),
    "sculk_shrieker": ("Sculk Shrieker", "スカルクシュライカー", "스컬크 비명체", "幽匿尖啸体"),
    "sculk_vein": ("Sculk Vein", "スカルクの葉脈", "스컬크 맥", "幽匿脉络"),
    "shelf": ("Shelf", "本棚", "선반", "展示架"),
    "shroomlight": ("Shroomlight", "シュルームライト", "버섯등", "菌光体"),
    "shulker_box": ("Shulker Box", "シュルカーボックス", "슈르커 상자", "潜影盒"),
    "slime_block": ("Slime Block", "スライムブロック", "슬라임 블록", "史莱姆块"),
    "small_amethyst_bud": ("Small Amethyst Bud", "小さなアメジストのつぼみ", "작은 자수정 새싹", "小型紫水晶芽"),
    "small_dripleaf": ("Small Dripleaf", "小さな雫草", "작은 방울풀", "小型垂滴叶"),
    "soul_sand": ("Soul Sand", "魂の砂", "영혼의 모래", "灵魂沙"),
    "soul_soil": ("Soul Soil", "魂の土", "영혼의 흙", "灵魂土"),
    "spawner": ("Spawner", "スポナー", "스포너", "刷怪笼"),
    "spore_blossom": ("Spore Blossom", "胞子の花", "포자 꽃", "孢子花"),
    "sponge": ("Sponge", "スポンジ", "스펀지", "海绵"),
    "stone": ("Stone", "石", "돌", "石头"),
    "stone_button": ("Stone Button", "石のボタン", "돌 버튼", "石按钮"),
    "stone_pressure_plate": ("Stone Pressure Plate", "石の感圧板", "돌 압력판", "石压力板"),
    "sulfur_spike": ("Sulfur Spike", "硫黄の棘", "황산 스파이크", "硫磺尖刺"),
    "sulfur": ("Sulfur", "硫黄", "황", "硫磺"),
    "potent_sulfur": ("Potent Sulfur", "強力な硫黄", "강력한 황", "强效硫磺"),
    "cinnabar": ("Cinnabar", "辰砂", "진사", "朱砂"),
    "sweet_berry_bush": ("Sweet Berry Bush", "甘いベリーの茂み", "달콤한 베리 덤불", "甜浆果丛"),
    "trial_spawner": ("Trial Spawner", "トライアルスポナー", "트라이얼 스포너", "试炼刷怪笼"),
    "tripwire": ("Tripwire", "トラップワイヤー", "트립와이어", "绊线"),
    "tuff": ("Tuff", "凝灰岩", "응회암", "凝灰岩"),
    "tuff_bricks": ("Tuff Bricks", "凝灰岩レンガ", "응회암 벽돌", "凝灰岩砖"),
    "polished_tuff": ("Polished Tuff", "磨いた凝灰岩", "연마된 응회암", "磨制凝灰岩"),
    "vault": ("Vault", "ヴォールト", "볼트", "宝库"),
    "vine": ("Vine", "蔦", "덩굴", "藤蔓"),
    "waxed_sign": ("Waxed Sign", "ワックス塗りの看板", "왁스 칠한 간판", "涂蜡告示牌"),
    "waxed_hanging_sign": ("Waxed Hanging Sign", "ワックス塗りのつるし看板", "왁스 칠한 매달린 간판", "涂蜡悬挂式告示牌"),
    "water": ("Water", "水", "물", "水"),
    "wet_grass": ("Wet Grass", "湿った草", "젖은 풀", "湿草"),
    "wet_sponge": ("Wet Sponge", "濡れたスポン지", "젖은 스펀지", "湿海绵"),
    "wooden_door": ("Wooden Door", "木のドア", "나무 문", "木门"),
    "wooden_trapdoor": ("Wooden Trapdoor", "木のトラップドア", "나무 다락문", "木活板门"),
    "wooden_button": ("Wooden Button", "木のボタン", "나무 버튼", "木按钮"),
    "wooden_pressure_plate": ("Wooden Pressure Plate", "木の感圧板", "나무 압력판", "木压力板"),
    "wood": ("Wood", "木材", "나무", "木头"),
    "wool": ("Wool", "羊毛", "양모", "羊毛"),
    "sign": ("Sign", "看板", "간판", "告示牌"),
}

# Entity name translations
EN = {
    "allay": ("Allay", "アレイ", "앨레이", "悦灵"),
    "armadillo": ("Armadillo", "アルマジロ", "아르마딜로", "犰狳"),
    "armor_stand": ("Armor Stand", "防具スタンド", "갑옷 거치대", "盔甲架"),
    "arrow": ("Arrow", "矢", "화살", "箭"),
    "axolotl": ("Axolotl", "ウーパールーパー", "엑소틀틀", "美西螈"),
    "bat": ("Bat", "コウモリ", "박쥐", "蝙蝠"),
    "bee": ("Bee", "ミツバチ", "꿀벌", "蜜蜂"),
    "blaze": ("Blaze", "ブレイズ", "블레이즈", "烈焰人"),
    "boat": ("Boat", "ボート", "보트", "船"),
    "bogged": ("Bogged", "ボグド", "보그드", "沼骸"),
    "breeze": ("Breeze", "ブリーズ", "브리즈", "旋风人"),
    "baby_cat": ("Baby Cat", "子猫", "새끼 고양이", "幼猫"),
    "baby_chicken": ("Baby Chicken", "子ひよこ", "새끼 병아리", "幼鸡"),
    "baby_horse": ("Baby Horse", "子馬", "새끼 말", "幼马"),
    "baby_pig": ("Baby Pig", "子豚", "새끼 돼지", "幼猪"),
    "baby_wolf": ("Baby Wolf", "子オオカミ", "새끼 늑대", "幼狼"),
    "baby_nautilus": ("Baby Nautilus", "子鹦鹉螺", "새끼 나우틸루스", "幼鹦鹉螺"),
    "camel_husk": ("Husk Camel", "ハスクラクダ", "허스크 낙타", "尸壳骆驼"),
    "camel": ("Camel", "ラクダ", "낙타", "骆驼"),
    "chicken": ("Chicken", "ヒヨコ", "병아리", "鸡"),
    "cod": ("Cod", "タラ", "대구", "鳕鱼"),
    "copper_golem": ("Copper Golem", "銅ゴーレム", "구리 골렘", "铜傀儡"),
    "copper_golem_weathered": ("Weathered Copper Golem", "風化した銅ゴーレム", "바랜 구리 골렘", "风化铜傀儡"),
    "copper_golem_oxidized": ("Oxidized Copper Golem", "酸化した銅ゴーレム", "산화된 구리 골렘", "氧化铜傀儡"),
    "cow": ("Cow", "ウシ", "소", "牛"),
    "creeper": ("Creeper", "クリーパー", "크리퍼", "苦力怕"),
    "creaking": ("Creaking", "軋む", "우장성", "嘎吱"),
    "dolphin": ("Dolphin", "イルカ", "돌고래", "海豚"),
    "donkey": ("Donkey", "ロバ", "당나귀", "驴"),
    "dragon_fireball": ("Dragon Fireball", "ドラゴンの火の球", "드래곤 화염탄", "龙火球"),
    "drowned": ("Drowned", "エンダーマン", "가라앉은 자", "溺尸"),
    "egg": ("Egg", "卵", "달걀", "鸡蛋"),
    "elder_guardian": ("Elder Guardian", "エルダーガーディアン", "엘더 가디언", "远古守卫者"),
    "ender_dragon": ("Ender Dragon", "エンダードラゴン", "엔더 드래곤", "末影龙"),
    "ender_eye": ("Ender Eye", "エンダーアイ", "엔더 아이", "末影之眼"),
    "enderman": ("Enderman", "エンダーマン", "엔더맨", "末影人"),
    "endermite": ("Endermite", "エンダーマイト", "엔더마이트", "末影螨"),
    "ender_pearl": ("Ender Pearl", "エンダーパール", "엔더 진주", "末影珍珠"),
    "evoker": ("Evoker", "エボーカー", "보카", "唤魔者"),
    "evoker_fangs": ("Evoker Fangs", "エボーカーの牙", "보카 이빨", "唤魔者之牙"),
    "experience_bottle": ("Experience Bottle", "経験瓶", "경험병", "经验瓶"),
    "experience_orb": ("Experience Orb", "経験値のオーブ", "경험치 구슬", "经验球"),
    "firework_rocket": ("Firework Rocket", "花火のロケット", "폭죽 로켓", "烟花火箭"),
    "fishing_bobber": ("Fishing Bobber", "フロート", "찌", "浮标"),
    "fox": ("Fox", "キツネ", "여우", "狐狸"),
    "frog": ("Frog", "カエル", "개구리", "青蛙"),
    "generic": ("Generic", "一般的", "일반", "通用"),
    "ghast": ("Ghast", "ガスト", "가스트", "恶魂"),
    "ghastling": ("Ghastling", "子ガスト", "새끼 가스트", "幼恶魂"),
    "glow_item_frame": ("Glow Item Frame", "光る額縁", "발광 액자", "荧光物品展示框"),
    "glow_squid": ("Glow Squid", "グロースィッド", "발광 오징어", "荧光鱿鱼"),
    "goat": ("Goat", "ヤギ", "염소", "山羊"),
    "guardian": ("Guardian", "ガーディアン", "가디언", "守卫者"),
    "happy_ghast": ("Happy Ghast", "ハッピーガスト", "행복한 가스트", "快乐恶魂"),
    "hoglin": ("Hoglin", "ホグリン", "호글린", "疣猪兽"),
    "horse": ("Horse", "馬", "말", "马"),
    "hostile": ("Hostile", "ホスト", "적대적", "敌对"),
    "husk": ("Husk", "ハスク", "허스크", "尸壳"),
    "illusioner": ("Illusioner", "イリュージョナー", "일루셔너", "幻术师"),
    "iron_golem": ("Iron Golem", "アイアンゴーレム", "아이언 골렘", "铁傀儡"),
    "item_frame": ("Item Frame", "額縁", "액자", "物品展示框"),
    "item": ("Item", "アイテム", "아이템", "物品"),
    "lightning_bolt": ("Lightning Bolt", "雷", "번개", "闪电"),
    "lingering_potion": ("Lingering Potion", "残留薬水", "잔류 물약", "滞留药水"),
    "llama": ("Llama", "ラマ", "라마", "羊驼"),
    "magma_cube": ("Magma Cube", "マグマキューブ", "마그마 큐브", "岩浆怪"),
    "minecart": ("Minecart", "トロッコ", "수레", "矿车"),
    "mooshroom": ("Mooshroom", "ムーシルーム", "우사", "哞菇"),
    "mule": ("Mule", "ラバ", "노새", "骡"),
    "nautilus": ("Nautilus", "鹦鹉螺", "나우틸루스", "鹦鹉螺"),
    "ocelot": ("Ocelot", "オセロット", "오셀롯", "豹猫"),
    "painting": ("Painting", "絵画", "그림", "画"),
    "panda": ("Panda", "パンダ", "팬더", "熊猫"),
    "parched": ("Parched", "パチェド", "마른", "干枯者"),
    "parrot": ("Parrot", "オウム", "앵무새", "鹦鹉"),
    "phantom": ("Phantom", "ファントム", "팬텀", "幻翼"),
    "pig": ("Pig", "豚", "돼지", "猪"),
    "piglin": ("Piglin", "ピグリン", "피글린", "猪灵"),
    "piglin_brute": ("Piglin Brute", "ピグリンブート", "피글린 부트", "猪灵蛮兵"),
    "pillager": ("Pillager", "ピリジャー", "플러저", "掠夺者"),
    "player": ("Player", "プレイヤー", "플레이어", "玩家"),
    "polar_bear": ("Polar Bear", "シロクマ", "북극곰", "北极熊"),
    "puffer_fish": ("Pufferfish", "フグ", "복어", "河豚"),
    "rabbit": ("Rabbit", "ウサギ", "토끼", "兔子"),
    "ravager": ("Ravager", "ラベイジャー", "레비저", "劫掠兽"),
    "salmon": ("Salmon", "サケ", "연어", "鲑鱼"),
    "sheep": ("Sheep", "ヒツジ", "양", "羊"),
    "shulker": ("Shulker", "シュルカー", "슈르커", "潜影贝"),
    "shulker_bullet": ("Shulker Bullet", "シュルカーブル", "슈르커 탄환", "潜影贝导弹"),
    "silverfish": ("Silverfish", "シルバーフィッシュ", "좀벌레", "蠹虫"),
    "skeleton": ("Skeleton", "スケルトン", "스켈레톤", "骷髅"),
    "skeleton_horse": ("Skeleton Horse", "スケルトンホース", "스켈레톤 말", "骷髅马"),
    "slime": ("Slime", "スライム", "슬라임", "史莱姆"),
    "small_sulfur_cube": ("Small Sulfur Cube", "小さな硫黄キューブ", "작은 황 큐브", "小硫磺块"),
    "snow_golem": ("Snow Golem", "スノーゴーレム", "스노우 골렘", "雪傀儡"),
    "snowball": ("Snowball", "雪玉", "눈덩이", "雪球"),
    "sulfur_cube": ("Sulfur Cube", "硫黄キューブ", "황 큐브", "硫磺块"),
    "spider": ("Spider", "クモ", "거미", "蜘蛛"),
    "splash_potion": ("Splash Potion", "スプラッシュポーション", "투척 물약", "喷溅药水"),
    "squid": ("Squid", "イカ", "오징어", "鱿鱼"),
    "strider": ("Strider", "ストライダー", "스트라이더", "炽足兽"),
    "stray": ("Stray", "ストレイ", "스트레이", "流浪者"),
    "tadpole": ("Tadpole", "オタマジャクシ", "올챙이", "蝌蚪"),
    "tnt": ("TNT", "TNT", "TNT", "TNT"),
    "turtle": ("Turtle", "カメ", "거북이", "海龟"),
    "vex": ("Vex", "ヴェックス", "벡스", "恼鬼"),
    "villager": ("Villager", "村人", "주민", "村民"),
    "vindicator": ("Vindicator", "ヴィンディケーター", "위ﾝ디케이터", "卫道士"),
    "wandering_trader": ("Wandering Trader", "放浪商人", "떠돌이 상인", "流浪商人"),
    "warden": ("Warden", "ウォーデン", "워든", "监守者"),
    "wind_charge": ("Wind Charge", "風のチャージ", "바람 차지", "风弹"),
    "witch": ("Witch", "魔女", "마녀", "女巫"),
    "wither": ("Wither", "ウィザー", "위더", "凋灵"),
    "wither_skeleton": ("Wither Skeleton", "ウィザースケル톤", "위더 스켈레톤", "凋灵骷髅"),
    "wolf": ("Wolf", "オオカミ", "늑대", "狼"),
    "zoglin": ("Zoglin", "ゾグリン", "조글린", "僵尸猪灵"),
    "zombie": ("Zombie", "ゾンビ", "좀비", "僵尸"),
    "zombie_horse": ("Zombie Horse", "ゾンビホース", "좀비 말", "僵尸马"),
    "zombie_nautilus": ("Zombie Nautilus", "ゾンビ鹦鹉螺", "좀비 나우틸루스", "僵尸鹦鹉螺"),
    "zombified_piglin": ("Zombified Piglin", "ゾンビ化ピグリン", "좀비화 피글린", "僵尸猪灵"),
    "zombie_villager": ("Zombie Villager", "ゾンビ村人", "좀비 주민", "僵尸村民"),
}

# Action translations: (en, ja, ko, zh)
ACT = {
    "break": ("Break", "を壊す", "부수기", "破碎"),
    "fall": ("Fall", "が落ちる", "떨어지기", "掉落"),
    "hit": ("Hit", "が当たる", "맞기", "击中"),
    "place": ("Place", "を設置", "놓기", "放置"),
    "step": ("Step", "を歩く", "걷기", "行走"),
    "close": ("Close", "を閉める", "닫기", "关闭"),
    "open": ("Open", "を開ける", "열기", "打开"),
    "click_off": ("Click Off", "OFF", "끄기", "松开"),
    "click_on": ("Click On", "ON", "켜기", "按下"),
    "ambient": ("Ambient", "の環境音", "환경음", "环境音"),
    "death": ("Death", "の死亡音", "죽음", "死亡"),
    "hurt": ("Hurt", "のダメージ音", "피해", "受伤"),
    "shoot": ("Shoot", "を発射", "발사", "射击"),
    "land": ("Land", "の着地音", "착지", "着地"),
    "destroy": ("Destroy", "の破壊音", "파괴", "破坏"),
    "use": ("Use", "の使用音", "사용", "使用"),
    "brew": ("Brew", "の醸造音", "양조", "酿造"),
    "activate": ("Activate", "の起動音", "활성화", "激活"),
    "deactivate": ("Deactivate", "の停止音", "비활성화", "停用"),
    "loop": ("Loop", "のループ音", "반복", "循环"),
    "idle": ("Idle", "の待機音", "대기", "待机"),
    "attack": ("Attack", "の攻撃音", "공격", "攻击"),
    "charge": ("Charge", "の充填音", "충전", "充能"),
    "deflect": ("Deflect", "の反射音", "반사", "偏转"),
    "inhale": ("Inhale", "の吸引音", "흡인", "吸入"),
    "jump": ("Jump", "のジャンプ音", "점프", "跳跃"),
    "slide": ("Slide", "のスライド音", "미끄러짐", "滑行"),
    "whirl": ("Whirl", "の渦音", "소용돌이", "旋涡"),
    "absorb": ("Absorb", "の吸収音", "흡수", "吸收"),
    "bounce": ("Bounce", "の跳ね音", "튐기", "弹跳"),
    "eject": ("Eject", "の排出音", "사출", "弹出"),
    "squish": ("Squish", "の潰れる音", "뭉개지기", "挤压"),
    "roll": ("Roll", "の転がり音", "굴리기", "滚动"),
    "spawn": ("Spawn", "のスポーン音", "스폰", "生成"),
    "shear": ("Shear", "の剪毛音", "털 깎기", "剪毛"),
    "insert": ("Insert", "の挿入音", "삽입", "插入"),
    "pick_berries": ("Pick Berries", "のベリー摘み音", "딸기 따기", "采摘浆果"),
    "extinguish": ("Extinguish", "の消火音", "소화", "熄灭"),
    "pop": ("Pop", "の破裂音", "팡 터지기", "破裂"),
    "craft": ("Craft", "のクラフト音", "제작", "合成"),
    "fail": ("Fail", "の失敗音", "실패", "失败"),
    "teleport": ("Teleport", "のテレポート音", "순간이동", "传送"),
    "eat": ("Eat", "の食べる音", "먹기", "进食"),
    "swim": ("Swim", "の泳ぎ音", "수영", "游泳"),
    "splash": ("Splash", "の水飛沫音", "물보라", "溅水"),
    "scream": ("Scream", "の悲鳴", "비명", "尖叫"),
    "warn": ("Warn", "の警告音", "경고", "警告"),
    "burn": ("Burn", "の燃焼音", "연소", "燃烧"),
    "pollinate": ("Pollinate", "の受粉音", "수분", "授粉"),
    "drip": ("Drip", "の滴音", "방울", "滴水"),
    "enter": ("Enter", "の侵入音", "진입", "进入"),
    "exit": ("Exit", "の脱出音", "이탈", "退出"),
    "tilt_down": ("Tilt Down", "の下傾き音", "아래로 기울이기", "下倾"),
    "tilt_up": ("Tilt Up", "の上傾き音", "위로 기울이기", "上倾"),
    "damage": ("Damage", "の損傷音", "손상", "损坏"),
    "repair": ("Repair", "の修理音", "수리", "修复"),
    "add_item": ("Add Item", "のアイテム追加音", "아이템 추가", "添加物品"),
    "remove_item": ("Remove Item", "のアイテム除去音", "아이템 제거", "移除物品"),
    "rotate_item": ("Rotate Item", "のアイテム回転音", "아이템 회전", "旋转物品"),
    "blow_up": ("Blow Up", "の膨らみ音", "부풀리기", "膨胀"),
    "blow_out": ("Blow Out", "の縮み音", "수축", "缩小"),
    "sting": ("Sting", "の針音", "독침", "蜇刺"),
    "paddle_land": ("Paddle Land", "の陸上漕ぎ音", "육상 노젓기", "陆上划桨"),
    "paddle_water": ("Paddle Water", "の水上漕ぎ音", "수상 노젓기", "水上划桨"),
    "takeoff": ("Takeoff", "の離陸音", "이륙", "起飞"),
    "loop_aggressive": ("Loop Aggressive", "の攻撃的ループ音", "공격적 반복", "攻击性循环"),
    "spawn_mob": ("Spawn Mob", "のスポーン音", "몹 스폰", "生成怪物"),
    "detect_player": ("Detect Player", "のプレイヤー検出音", "플레이어 감지", "检测玩家"),
    "ominous_activate": ("Ominous Activate", "の不吉な起動音", "불길한 활성화", "不祥激活"),
    "ambient_ominous": ("Ambient Ominous", "の不吉な環境音", "불길한 환경음", "不祥环境音"),
    "open_shutter": ("Open Shutter", "のシャッター開放音", "셔터 열기", "打开百叶窗"),
    "close_shutter": ("Close Shutter", "のシャッター閉鎖音", "셔터 닫기", "关闭百叶窗"),
    "eject_item": ("Eject Item", "のアイテム射出音", "아이템 사출", "弹射物品"),
    "smoke": ("Smoke", "の煙音", "연기", "冒烟"),
    "insert_fail": ("Insert Fail", "の挿入失敗音", "삽입 실패", "插入失败"),
    "shatter": ("Shatter", "の破砕音", "산산조각", "粉碎"),
    "sculk_spread": ("Sculk Spread", "の広がり音", "퍼지기", "幽匿蔓延"),
    "sculk_charge": ("Sculk Charge", "の充填音", "충전", "幽匿充能"),
    "sculk_clicking": ("Sculk Clicking", "のクリック音", "클릭", "幽匿点击"),
    "sculk_clicking_stop": ("Sculk Clicking Stop", "のクリック停止音", "클릭 중지", "幽匿点击停止"),
    "bloom": ("Bloom", "の開花音", "개화", "绽放"),
    "impact": ("Impact", "の衝撃音", "충격", "撞击"),
    "thunder": ("Thunder", "の雷鳴", "천둥", "雷鸣"),
    "wind_burst": ("Wind Burst", "の風の爆発音", "바람 폭발", "风之爆发"),
    "dash": ("Dash", "のダッシュ音", "대시", "冲刺"),
    "dash_ready": ("Dash Ready", "のダッシュ準備音", "대시 준비", "冲刺就绪"),
    "sit": ("Sit", "の座る音", "앉기", "坐下"),
    "stand": ("Stand", "の立つ音", "일어서기", "站立"),
    "step_sand": ("Step Sand", "の砂上歩行音", "모래 위 걷기", "沙上行走"),
    "convert": ("Convert", "の変化音", "변환", "转换"),
    "milk": ("Milk", "の搾乳音", "착유", "挤奶"),
    "cast_spell": ("Cast Spell", "の呪文詠唱音", "주문 시전", "施法"),
    "celebrate": ("Celebrate", "の祝祭音", "축하", "庆祝"),
    "prepare_attack": ("Prepare Attack", "の攻撃準備音", "공격 준비", "准备攻击"),
    "prepare_summon": ("Prepare Summon", "の召喚準備音", "소환 준비", "准备召唤"),
    "throw": ("Throw", "の投げ音", "던지기", "投掷"),
    "flop": ("Flop", "の跳ね音", ")reader", "扑腾"),
    "sniff": ("Sniff", "の嗅ぎり音", "냄새 맡기", "嗅探"),
    "bite": ("Bite", "の噛みつき音", "물기", "咬"),
    "lay_spawn": ("Lay Spawn", "の産卵音", "알 낳기", "产卵"),
    "tongue": ("Tongue", "の舌音", "혀", "舌头"),
    "long_jump": ("Long Jump", "の長距離ジャンプ音", "멀리뛰기", "远跳"),
    "dig": ("Dig", "の掘削音", "파기", "挖掘"),
    "emerge": ("Emerge", "の出現音", "출현", "出现"),
    "heartbeat": ("Heartbeat", "の心臓の鼓動", "심장 박동", "心跳"),
    "agitated": ("Agitated", "の烦躁音", "짜증", "烦躁"),
    "sonic_boom": ("Sonic Boom", "のソニックブーム", "소닉 붐", "音速轰鸣"),
    "block": ("Block", "のブロック音", "블록", "格挡"),
    "levelup": ("Level Up", "のレベルアップ音", "레벨 업", "升级"),
    "big_fall": ("Big Fall", "の大落下音", "큰 낙하", "大量坠落"),
    "small_fall": ("Small Fall", "の小落下音", "작은 낙하", "少量坠落"),
    "hurt_drown": ("Hurt Drown", "の溺れダメージ音", "익사 피해", "溺水受伤"),
    "hurt_freeze": ("Hurt Freeze", "の凍結ダメージ音", "동결 피해", "冻伤"),
    "breath": ("Breath", "の息遣い", "숨결", "呼吸"),
    "burp": ("Burp", "のゲップ音", "트림", "打嗝"),
    "attack_crit": ("Crit", "のクリティカル攻撃", "크리티컬", "暴击"),
    "attack_knockback": ("Knockback", "のノックバック攻撃", "넉백", "击退"),
    "attack_nodamage": ("No Damage", "の無ダメージ攻撃", "데미지 없음", "无伤害"),
    "attack_strong": ("Strong", "の強攻撃", "강한 공격", "强攻击"),
    "attack_sweep": ("Sweep", "の薙ぎ払い攻撃", "베기", "横扫"),
    "attack_weak": ("Weak", "の弱攻撃", "약한 공격", "弱攻击"),
    "trade": ("Trade", "の交易音", "거래", "交易"),
    "no": ("No", "の拒否音", "거절", "拒绝"),
    "yes": ("Yes", "の承諾音", "수락", "同意"),
    "disappeared": ("Disappeared", "の消失音", "소멸", "消失"),
    "reappeared": ("Reappeared", "の再出現音", "재출현", "重新出现"),
    "scenting": ("Scenting", "の嗅ぎり開始音", "냄새 맡기 시작", "嗅探开始"),
    "sniffing": ("Sniffing", "の嗅ぎり音", "냄새 맡기", "嗅探中"),
    "searching": ("Searching", "の探索音", "탐색", "搜索中"),
    "digging": ("Digging", "の掘削音", "파기", "挖掘中"),
    "digging_stop": ("Digging Stop", "の掘削停止音", "파기 중지", "挖掘停止"),
    "happy": ("Happy", "の喜び音", "기쁨", "高兴"),
    "plop": ("Plop", "のドロップ音", "통落ち", "扑通"),
    "crack": ("Crack", "のひび割れ音", "금 갈라짐", "破裂"),
    "hatch": ("Hatch", "の孵化音", "부화", "孵化"),
    "destroy_egg": ("Destroy Egg", "の卵破壊音", "알 파괴", "破坏蛋"),
    "infect": ("Infect", "の感染音", "감염", "感染"),
    "egg_break": ("Egg Break", "の卵割れ音", "알 깨짐", "蛋破碎"),
    "egg_crack": ("Egg Crack", "の卵ひび割れ音", "알 금 갈라짐", "蛋裂开"),
    "egg_hatch": ("Egg Hatch", "の卵孵化音", "알 부화", "蛋孵化"),
    "lay_egg": ("Lay Egg", "の産卵音", "알 낳기", "下蛋"),
    "shamble": ("Shamble", "のよろめき音", "비틀거리기", "蹒跚"),
    "warning": ("Warning", "の警告音", "경고", "警告"),
    "stunned": ("Stunned", "の気絶音", "기절", "眩晕"),
    "roar": ("Roar", "の咆哮音", "포효", "咆哮"),
    "tendril_clicks": ("Tendril Clicks", "の触手クリック音", "촉수 클릭", "触手点击"),
    "nearby_close": ("Nearby Close", "の近い音", "가까이", "近处"),
    "nearby_closer": ("Nearby Closer", "の更に近い音", "더 가까이", "更近"),
    "nearby_closest": ("Nearby Closest", "の最も近い音", "가장 가까이", "最近"),
    "listening": ("Listening", "の聴取音", "듣기", "聆听"),
    "list": ("List", "のリスト音", "목록", "列表"),
    "make_cookie": ("Make Cookie", "のクッキー作り音", "쿠키 만들기", "制作曲奇"),
    "shrine": ("Shrine", "の神社音", "신사", "神社"),
    "revive": ("Revive", "の蘇生音", "부활", "复活"),
    "ride": ("Ride", "の乗る音", "말타기", "骑乘"),
    "riding": ("Riding", "の乗っている音", "말타기 중", "乘坐中"),
    "equip": ("Equip", "の装備音", "장비", "装备"),
    "unequip": ("Unequip", "の装備解除音", "장비 해제", "卸下装备"),
    "harness_goggles_up": ("Harness Goggles Up", "のゴーグル上げ音", "고글 올리기", "护目镜上推"),
    "harness_goggles_down": ("Harness Goggles Down", "のゴーグル下げ音", "고글 내리기", "护目镜下拉"),
    "apply_effect": ("Apply Effect", "のエフェクト付与音", "효과 부여", "施加效果"),
    "stir": ("Stir", "のかき混ぜ音", "섞기", "搅拌"),
    "flat": ("Flat", "の平らな音", "평평한", "扁平"),
    "sharp": ("Sharp", "の鋭い音", "날카로운", "锋利"),
    "drop_seed": ("Drop Seed", "の種落とし音", "씨앗 떨어뜨리기", "掉落种子"),
    "chunk_load": ("Chunk Load", "のチャンク読込音", "청크 로드", "区块加载"),
    "uncover": ("Uncover", "の覆い取り音", "덮개 벗기기", "揭开"),
    "spawn_statue": ("Spawn Statue", "の像スポーン音", "동상 스폰", "生成雕像"),
    "smash_air": ("Smash Air", "の空中叩きつけ音", "공중 내리치기", "空中猛击"),
    "smash_ground": ("Smash Ground", "の地面叩きつけ音", "지면 내리치기", "地面猛击"),
    "smash_ground_heavy": ("Smash Ground Heavy", "の重地面叩きつけ音", "강력 지면 내리치기", "重击地面"),
    "scute_drop": ("Scute Drop", "の鱗落ち音", "비늘 떨어짐", "鳞片掉落"),
    "chime": ("Chime", "のチャイム音", "차임벨", "钟声"),
    "resonate": ("Resonate", "の共鳴音", "공명", "共鸣"),
    "retract": ("Retract", "の収縮音", "수축", "收回"),
}




# Manual overrides for sounds that need special translations
MANUAL_OVERRIDES = {
    "ambient.cave": t("Cave: eerie noise", "洞窟の不気味な音", "동굴：기괴한 소음", "洞穴：怪异的噪声"),
    "ambient.underwater.enter": t("Underwater: enter", "水中に入る音", "수중：진입", "入水"),
    "ambient.underwater.exit": t("Underwater: exit", "水中から出る音", "수중：이탈", "出水"),
    "ambient.underwater.loop": t("Underwater: loop", "水中ループ音", "수중：반복", "水下循环"),
    "ambient.underwater.loop.additions": t("Underwater: additions", "水中追加音", "수중：추가", "水下附加音"),
    "ambient.underwater.loop.additions.rare": t("Underwater: rare additions", "水中希少追加音", "수중：희귀 추가", "水下稀有附加音"),
    "ambient.underwater.loop.additions.ultra_rare": t("Underwater: ultra rare additions", "水中極希少追加音", "수중：극히 희귀 추가", "水下极稀有附加音"),
    "ambient.basalt_deltas.additions": t("Basalt Deltas: ambient additions", "玄武岩デルタの環境追加音", "현무암 삼각주：환경 추가 음향", "玄武岩三角洲：环境附加音效"),
    "ambient.basalt_deltas.loop": t("Basalt Deltas: ambient loop", "玄武岩デルタの環境ループ音", "현무암 삼각주：환경 반복 음향", "玄武岩三角洲：环境循环音效"),
    "ambient.basalt_deltas.mood": t("Basalt Deltas: eerie noise", "玄武岩デルタの不気味な音", "현무암 삼각주：기괴한 소음", "玄武岩三角洲：怪异的噪声"),
    "ambient.crimson_forest.additions": t("Crimson Forest: ambient additions", "真紅の森の環境追加音", "진홍빛 숲：환경 추가 음향", "绯红森林：环境附加音效"),
    "ambient.crimson_forest.loop": t("Crimson Forest: ambient loop", "真紅の森の環境ループ音", "진홍빛 숲：환경 반복 음향", "绯红森林：环境循环音效"),
    "ambient.crimson_forest.mood": t("Crimson Forest: eerie noise", "真紅の森の不気味な音", "진홍빛 숲：기괴한 소음", "绯红森林：怪异的噪声"),
    "ambient.nether_wastes.additions": t("Nether Wastes: ambient additions", "ネザーの荒れ地の環境追加音", "지옥：환경 추가 음향", "下界荒地：环境附加音效"),
    "ambient.nether_wastes.loop": t("Nether Wastes: ambient loop", "ネザーの荒れ地の環境ループ音", "지옥：환경 반복 음향", "下界荒地：环境循环音效"),
    "ambient.nether_wastes.mood": t("Nether Wastes: eerie noise", "ネザーの荒れ地の不気味な音", "지옥：기괴한 소음", "下界荒地：怪异的噪声"),
    "ambient.soul_sand_valley.additions": t("Soul Sand Valley: ambient additions", "魂の砂の谷の環境追加音", "혼의 모래 계곡：환경 추가 음향", "灵魂沙峡谷：环境附加音效"),
    "ambient.soul_sand_valley.loop": t("Soul Sand Valley: ambient loop", "魂の砂の谷の環境ループ音", "혼의 모래 계곡：환경 반복 음향", "灵魂沙峡谷：环境循环音效"),
    "ambient.soul_sand_valley.mood": t("Soul Sand Valley: eerie noise", "魂の砂の谷の不気味な音", "혼의 모래 계곡：기괴한 소음", "灵魂沙峡谷：怪异的噪声"),
    "ambient.warped_forest.additions": t("Warped Forest: ambient additions", "歪んだ森の環境追加音", "뒤틀린 숲：환경 추가 음향", "诡异森林：环境附加音效"),
    "ambient.warped_forest.loop": t("Warped Forest: ambient loop", "歪んだ森の環境ループ音", "뒤틀린 숲：환경 반복 음향", "诡异森林：环境循环音效"),
    "ambient.warped_forest.mood": t("Warped Forest: eerie noise", "歪んだ森の不気味な音", "뒤틀린 숲：기괴한 소음", "诡异森林：怪异的噪声"),
    "weather.rain": t("Rain", "雨音", "비 소리", "雨声"),
    "weather.rain.above": t("Rain: above", "空からの雨音", "위：비 소리", "高空雨声"),
    "weather.end_flash": t("End: flash", "エンドの閃光音", "엔드：번개", "末地闪光"),
    "ui.button.click": t("Button: click", "ボタンのクリック音", "버튼：클릭", "按钮：点击"),
    "ui.hud.bubble_pop": t("Bubble pop", "泡が弾ける音", "거품 터짐", "气泡破裂"),
    "ui.toast.challenge_complete": t("Challenge complete", "チャレンジ完了", "도전 완료", "挑战完成"),
    "ui.toast.in": t("Toast: in", "トースト：表示", "토스트：표시", "弹窗：进入"),
    "ui.toast.out": t("Toast: out", "トースト：非表示", "토스트：비표시", "弹窗：消失"),
    "ui.loom.select_pattern": t("Loom: select pattern", "織機：模様選択", "베틀：패턴 선택", "织布机：选择图案"),
    "ui.loom.take_result": t("Loom: take result", "織機：結果を受け取る", "베틀：결과 수령", "织布机：取走结果"),
    "ui.cartography_table.take_result": t("Cartography table: take result", "製図台：結果を受け取る", "제도대：결과 수령", "制图台：取走结果"),
    "ui.stonecutter.select_recipe": t("Stonecutter: select recipe", "石切台：レシピ選択", "석재절단기：레시피 선택", "切石机：选择配方"),
    "ui.stonecutter.take_result": t("Stonecutter: take result", "石切台：結果を受け取る", "석재절단기：결과 수령", "切石机：取走结果"),
    "particle.soul_escape": t("Soul: escape", "魂の逃走音", "영혼：탈출", "灵魂：逃逸"),
    "music.creative": t("Music: creative", "音楽：クリエイティブ", "음악：크리에이티브", "音乐：创造模式"),
    "music.credits": t("Music: credits", "音楽：クレジット", "음악：크레딧", "音乐：制作人员"),
    "music.dragon": t("Music: dragon", "音楽：ドラゴン戦", "음악：드래곤 전투", "音乐：龙战"),
    "music.end": t("Music: end", "音楽：エンド", "음악：엔드", "音乐：末地"),
    "music.game": t("Music: game", "音楽：ゲーム", "음악：게임", "音乐：游戏"),
    "music.menu": t("Music: menu", "音楽：メニュー", "음악：메뉴", "音乐：菜单"),
    "music.under_water": t("Music: underwater", "音楽：水中", "음악：수중", "音乐：水下"),
    "music.nether.basalt_deltas": t("Music: basalt deltas", "音楽：玄武岩デルタ", "음악：현무암 삼각주", "音乐：玄武岩三角洲"),
    "music.nether.crimson_forest": t("Music: crimson forest", "音楽：真紅の森", "음악：진홍빛 숲", "音乐：绯红森林"),
    "music.nether.nether_wastes": t("Music: nether wastes", "音楽：ネザーの荒れ地", "음악：지옥 황야", "音乐：下界荒地"),
    "music.nether.soul_sand_valley": t("Music: soul sand valley", "音楽：魂の砂の谷", "음악：혼의 모래 계곡", "音乐：灵魂沙峡谷"),
    "music.nether.warped_forest": t("Music: warped forest", "音楽：歪んだ森", "음악：뒤틀린 숲", "音乐：诡异森林"),
    "music.overworld.badlands": t("Music: badlands", "音楽：悪地", "음악：황야", "音乐：恶地"),
    "music.overworld.bamboo_jungle": t("Music: bamboo jungle", "音楽：竹林", "음악：대나무 정글", "音乐：竹林"),
    "music.overworld.cherry_grove": t("Music: cherry grove", "音楽：桜の森", "음악：벚꽃 숲", "音乐：樱花树林"),
    "music.overworld.deep_dark": t("Music: deep dark", "音楽：ディープダーク", "음악：딥 다크", "音乐：深暗之域"),
    "music.overworld.desert": t("Music: desert", "音楽：砂漠", "음악：사막", "音乐：沙漠"),
    "music.overworld.dripstone_caves": t("Music: dripstone caves", "音楽：滴り石の洞窟", "음악：드롭스톤 동굴", "音乐：滴水石洞"),
    "music.overworld.flower_forest": t("Music: flower forest", "音楽：花の森", "음악：꽃 숲", "音乐：繁花森林"),
    "music.overworld.forest": t("Music: forest", "音楽：森", "음악：숲", "音乐：森林"),
    "music.overworld.frozen_peaks": t("Music: frozen peaks", "音楽：凍てつく頂", "음악：얼어붙은 봉우리", "音乐：冻封山峰"),
    "music.overworld.grove": t("Music: grove", "音楽：樹林", "음악：숲속", "音乐：树林"),
    "music.overworld.jagged_peaks": t("Music: jagged peaks", "音楽：ギザギザの頂", "음악：거친 봉우리", "音乐：锯齿山峰"),
    "music.overworld.jungle": t("Music: jungle", "音楽：ジャングル", "음악：정글", "音乐：丛林"),
    "music.overworld.lush_caves": t("Music: lush caves", "音楽：翠の洞窟", "음악：울창한 동굴", "音乐：繁茂洞穴"),
    "music.overworld.meadow": t("Music: meadow", "音楽：牧草地", "음악：초원", "音乐：草甸"),
    "music.overworld.old_growth_taiga": t("Music: old growth taiga", "音楽：古木のタイガ", "음악：오래된 타이가", "音乐：原始针叶林"),
    "music.overworld.sparse_jungle": t("Music: sparse jungle", "音楽：疎林", "음악：드문드문한 정글", "音乐：稀疏丛林"),
    "music.overworld.snowy_slopes": t("Music: snowy slopes", "音楽：雪の斜面", "음악：눈 덮인 경사면", "音乐：积雪山坡"),
    "music.overworld.stony_peaks": t("Music: stony peaks", "音楽：岩の頂", "음악：바위 봉우리", "音乐：岩石山峰"),
    "music.overworld.swamp": t("Music: swamp", "音楽：沼地", "음악：늪지", "音乐：沼泽"),
    "music.overworld.sulfur_caves": t("Music: sulfur caves", "音楽：硫黄の洞窟", "음악：황 동굴", "音乐：硫磺洞穴"),
}


def make_auto_translation(sound_id):
    """Generate automatic translations for a sound event based on its components."""
    parts = sound_id.split(".")
    en_parts, ja_parts, ko_parts, zh_parts = [], [], [], []
    for p in parts:
        if p in ACT:
            e, j, k, z = ACT[p]
            en_parts.append(e)
            ja_parts.append(j)
            ko_parts.append(k)
            zh_parts.append(z)
        elif p in BN:
            e, j, k, z = BN[p]
            en_parts.append(e)
            ja_parts.append(j)
            ko_parts.append(k)
            zh_parts.append(z)
        elif p in EN:
            e, j, k, z = EN[p]
            en_parts.append(e)
            ja_parts.append(j)
            ko_parts.append(k)
            zh_parts.append(z)
        else:
            title = p.replace("_", " ").title()
            en_parts.append(title)
            ja_parts.append(p)
            ko_parts.append(p)
            zh_parts.append(p)
    return t(" ".join(en_parts), "".join(ja_parts), " ".join(ko_parts), "".join(zh_parts))


def main():
    be_sounds = read_be_translations()
    je_ids = extract_je_sound_ids()

    result = {}

    for sound_id in je_ids:
        if sound_id in be_sounds:
            result[sound_id] = be_sounds[sound_id]
        elif sound_id in MANUAL_OVERRIDES:
            result[sound_id] = MANUAL_OVERRIDES[sound_id]
        else:
            result[sound_id] = make_auto_translation(sound_id)

    out_path = os.path.join(os.path.dirname(__file__), "je_sounds.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    print(f"Generated {out_path} with {len(result)} sounds")


if __name__ == "__main__":
    main()
