enchantments = {
    "protection": {"numberId": 0, **t("Protection", "防御", "방어", "保护")},
    "fire_protection": {"numberId": 1, **t("Fire Protection", "火炎耐性", "화염 방어", "火焰保护")},
    "feather_falling": {"numberId": 2, **t("Feather Falling", "落下耐性", "깃털 낙하", "摔落缓冲")},
    "blast_protection": {"numberId": 3, **t("Blast Protection", "爆発耐性", "폭발 방어", "爆炸保护")},
    "projectile_protection": {"numberId": 4, **t("Projectile Protection", "飛び道具耐性", "투사체 방어", "弹射物保护")},
    "thorns": {"numberId": 5, **t("Thorns", "棘", "가시", "荆棘")},
    "respiration": {"numberId": 6, **t("Respiration", "水中呼吸", "수중 호흡", "水下呼吸")},
    "aqua_affinity": {"numberId": 7, **t("Aqua Affinity", "水中適応", "물의 친화", "水下速掘")},
    "depth_strider": {"numberId": 8, **t("Depth Strider", "深海の歩き手", "심해 탐험가", "深海探索者")},
    "sharpness": {"numberId": 9, **t("Sharpness", "鋭锋", "날카로움", "锋利")},
    "smite": {"numberId": 10, **t("Smite", "アンデッド討伐", "언데드 학살", "亡灵杀手")},
    "bane_of_arthropods": {"numberId": 11, **t("Bane of Arthropods", "虫殺し", "절지동물 학살", "节肢杀手")},
    "knockback": {"numberId": 12, **t("Knockback", "ノックバック", "넉백", "击退")},
    "fire_aspect": {"numberId": 13, **t("Fire Aspect", "炎の付与", "화염 속성", "火焰附加")},
    "looting": {"numberId": 14, **t("Looting", "掠奪", "약탈", "抢夺")},
    "sweeping_edge": {"numberId": 15, **t("Sweeping Edge", "横切り刃", "휩쓸기", "横扫之刃")},
    "efficiency": {"numberId": 16, **t("Efficiency", "効率強化", "효율", "效率")},
    "silk_touch": {"numberId": 17, **t("Silk Touch", "シルクタッチ", "실크 손길", "精准采集")},
    "unbreaking": {"numberId": 18, **t("Unbreaking", "耐久力", "내구성", "耐久")},
    "fortune": {"numberId": 19, **t("Fortune", "幸運", "행운", "时运")},
    "power": {"numberId": 20, **t("Power", "パワー", "힘", "力量")},
    "punch": {"numberId": 21, **t("Punch", "衝撃", "타격", "冲击")},
    "flame": {"numberId": 22, **t("Flame", "燃焼", "화염", "火矢")},
    "infinity": {"numberId": 23, **t("Infinity", "無限", "무한", "无限")},
    "luck_of_the_sea": {"numberId": 24, **t("Luck of the Sea", "海の恵み", "바다의 은총", "海之眷顾")},
    "lure": {"numberId": 25, **t("Lure", "誘引", "미끼", "饵钓")},
    "frost_walker": {"numberId": 26, **t("Frost Walker", "霜の歩き手", "서리 걷는 자", "冰霜行者")},
    "mending": {"numberId": 27, **t("Mending", "修繕", "수선", "经验修补")},
    "binding_curse": {"numberId": 28, **t("Binding Curse", "束縛の呪い", "귀속의 저주", "绑定诅咒")},
    "vanishing_curse": {"numberId": 29, **t("Vanishing Curse", "消滅の呪い", "소멸의 저주", "消失诅咒")},
    "impaling": {"numberId": 30, **t("Impaling", "突き刺し", "관통", "穿刺")},
    "riptide": {"numberId": 31, **t("Riptide", "激流", "역류", "激流")},
    "loyalty": {"numberId": 32, **t("Loyalty", "忠誠", "충성", "忠诚")},
    "channeling": {"numberId": 33, **t("Channeling", "召雷", "번개 소환", "引雷")},
    "multishot": {"numberId": 34, **t("Multishot", "多弾発射", "다중 발사", "多重射击")},
    "quick_charge": {"numberId": 35, **t("Quick Charge", "急速装填", "빠른 장전", "快速装填")},
    "piercing": {"numberId": 36, **t("Piercing", "貫通", "관통", "穿透")},
    "soul_speed": {"numberId": 37, **t("Soul Speed", "ソウルスピード", "영혼의 속도", "灵魂疾行")},
    "swift_sneak": {"numberId": 38, **t("Swift Sneak", "素早い潜行", "빠른 은신", "迅捷潜行")},
    "wind_burst": {"numberId": 39, **t("Wind Burst", "風爆", "바람 폭발", "风爆")},
    "density": {"numberId": 40, **t("Density", "密度", "밀도", "致密")},
    "breach": {"numberId": 41, **t("Breach", "突破", "갑옷 파괴", "破甲")},
    "lunge": {"numberId": 42, **t("Lunge", "突進", "돌진", "突进")},
}
